eclipse-iceoryx/iceoryx2

Cargo.toml
benchmarks/publish_subscribe/Cargo.toml
examples/Cargo.toml
iceoryx2/Cargo.toml
iceoryx2_bb/container/Cargo.toml
iceoryx2_bb/elementary/Cargo.toml
iceoryx2_bb/lock_free/Cargo.toml
iceoryx2_bb/log/Cargo.toml
iceoryx2_bb/memory/Cargo.toml
iceoryx2_bb/posix/Cargo.toml
iceoryx2_bb/system_types/Cargo.toml
iceoryx2_bb/testing/Cargo.toml
iceoryx2_bb/threadsafe/Cargo.toml
iceoryx2_cal/Cargo.toml
iceoryx2_pal/concurrency_primitives/Cargo.toml
iceoryx2_pal/posix/Cargo.toml
iceoryx2_pal/settings/Cargo.toml

[#2] Add tags to cargo

---

Cargo.toml
iceoryx2-bb/container/Cargo.toml
iceoryx2-bb/container/src/queue.rs
iceoryx2-bb/container/src/vec.rs
iceoryx2-bb/container/tests/queue_tests.rs
iceoryx2-bb/container/tests/vec_tests.rs
iceoryx2-bb/elementary/src/bump_allocator.rs
iceoryx2-bb/elementary/src/lib.rs
iceoryx2-bb/lock-free/Cargo.toml
iceoryx2-bb/lock-free/src/mpmc/unique_index_set.rs
iceoryx2-bb/lock-free/tests/mpmc_container_tests.rs
iceoryx2-bb/lock-free/tests/mpmc_unique_index_set_tests.rs
iceoryx2-pal/posix/build.rs
iceoryx2-pal/posix/src/c/posix_docs_rs.h

[#31] Solve circular dependency

---

internal/scripts/crates_io_publish_script.sh

[#34] Add publish script

---

iceoryx2/src/lib.rs

[#36] Correct github links

---

Cargo.toml
ROADMAP.md

[#2] Set version to 0.1.0

---

README.md
iceoryx2/src/lib.rs

[#2] Add shields and correct link

---

CONTRIBUTING.md

[#2] Fill contributing.md file

---

iceoryx2-bb/posix/tests/condition_variable_tests.rs
iceoryx2-pal/concurrency-sync/src/condition_variable.rs
iceoryx2-pal/concurrency-sync/src/lib.rs
iceoryx2-pal/concurrency-sync/src/mutex.rs
iceoryx2-pal/concurrency-sync/src/rwlock.rs
iceoryx2-pal/concurrency-sync/src/semaphore.rs
iceoryx2-pal/concurrency-sync/tests/condition_variable_tests.rs
iceoryx2-pal/concurrency-sync/tests/mutex_tests.rs
iceoryx2-pal/concurrency-sync/tests/rwlock_tests.rs
iceoryx2-pal/concurrency-sync/tests/semaphore_tests.rs
iceoryx2-pal/posix/src/macos/pthread.rs
iceoryx2-pal/posix/src/macos/semaphore.rs
iceoryx2-pal/posix/src/windows/pthread.rs
iceoryx2-pal/posix/src/windows/semaphore.rs
iceoryx2-pal/posix/src/windows/signal.rs
iceoryx2-pal/posix/src/windows/win32_handle_translator.rs

This is the first of some PR for mac os support. In this PR the mac os condition variable is finalized by using a low level semaphore based on atomics and atomic wait operations.
1. [x] All checks have passed (except …

iox2-51 integrate posix condition variable for mac os

---

.cirrus.yml
README.md
ROADMAP.md
doc/release-notes/iceoryx2-unreleased.md
iceoryx2-bb/posix/src/condition_variable.rs
iceoryx2-bb/posix/src/thread.rs
iceoryx2-bb/posix/tests/condition_variable_tests.rs
iceoryx2-bb/posix/tests/mutex_tests.rs
iceoryx2-bb/posix/tests/shared_memory_tests.rs
iceoryx2-bb/threadsafe/tests/trigger_queue_tests.rs
iceoryx2-cal/src/event/process_local.rs
iceoryx2-pal/concurrency-sync/tests/condition_variable_tests.rs
iceoryx2-pal/posix/src/macos/mman.rs
iceoryx2/tests/service_publish_subscribe_tests.rs

Do not review before #52 is merged, since it is based on it.
MacOS has the restrictions that only 31 characters are allowed for the shared memory name but iceoryx2 requires much more. The trick is that a file is created to:
* be able to list all shared memorys in mac os (already present)
* store the actual shm name, the file name corresponds to the user given shared memory name
In the file is then the triple stored (`$PID$_$TIMESTAMP_SECS$_$TIMESTAMP_NSEC$`). In the worst case scenario where PID + SEC is larger than 1.000.000.000 it would hit the max name length of mac os (32 > 31), but to our luck NSEC is always smaller than 1.000.000.000 giving us the extra character we need.
1. [x] Relevant …

iox2-51 shm long name support

---

ROADMAP.md
doc/release-notes/iceoryx2-unreleased.md
iceoryx2-bb/container/src/byte_string.rs
iceoryx2-bb/container/tests/byte_string_tests.rs
iceoryx2-bb/posix/src/mutex.rs
iceoryx2-bb/posix/tests/mutex_tests.rs

[#56] Introduce `from_bytes_truncated`

---

doc/release-notes/iceoryx2-unreleased.md
iceoryx2-bb/container/src/vec.rs
iceoryx2-bb/container/tests/vec_tests.rs

Please review #57 first since this PR is based on it.
[eca]: …

[#58] add functionality to vec

---

ROADMAP.md
doc/release-notes/iceoryx2-unreleased.md
iceoryx2-bb/posix/tests/udp_socket_tests.rs
iceoryx2/src/service/config_scheme.rs
iceoryx2/src/service/messaging_pattern.rs

[#64] Implement Display for MessagingPattern

---

.cirrus.yml
doc/release-notes/iceoryx2-unreleased.md
internal/docker/archlinux-base-devel
internal/docker/ubuntu-22.04

[#48] Adding audit scripts

---

iceoryx2-bb/posix/src/signal.rs
iceoryx2-pal/posix/src/windows/types.rs

[#81] Add better log error output for signal handler failure

---

doc/release-notes/iceoryx2-unreleased.md
iceoryx2-bb/lock-free/src/spsc/index_queue.rs
iceoryx2-bb/lock-free/src/spsc/queue.rs
iceoryx2-bb/lock-free/src/spsc/safely_overflowing_index_queue.rs

[#87] Fix undefined behavior in spsc {queue|index_queue}

---

doc/release-notes/iceoryx2-unreleased.md
iceoryx2-bb/system-types/src/path.rs
iceoryx2-cal/src/zero_copy_connection/mod.rs
iceoryx2-cal/src/zero_copy_connection/posix_shared_memory.rs
iceoryx2-cal/src/zero_copy_connection/process_local.rs
iceoryx2/src/port/details/publisher_connections.rs
iceoryx2/src/port/details/subscriber_connections.rs
iceoryx2/src/port/listener.rs
iceoryx2/src/port/notifier.rs
iceoryx2/src/port/publisher.rs
iceoryx2/src/port/subscriber.rs
iceoryx2/src/prelude.rs
iceoryx2/src/service/builder/event.rs
iceoryx2/src/service/builder/mod.rs
iceoryx2/src/service/builder/publish_subscribe.rs
iceoryx2/src/service/config_scheme.rs
iceoryx2/src/service/mod.rs
iceoryx2/src/service/port_factory/event.rs
iceoryx2/src/service/port_factory/listener.rs
iceoryx2/src/service/port_factory/notifier.rs
iceoryx2/src/service/port_factory/publish_subscribe.rs
iceoryx2/src/service/port_factory/publisher.rs
iceoryx2/src/service/port_factory/subscriber.rs
iceoryx2/src/service/process_local.rs
iceoryx2/src/service/zero_copy.rs
iceoryx2/tests/service_event_tests.rs
iceoryx2/tests/service_publish_subscribe_tests.rs

Just removed the `'config` lifetime and handled the config ownership with a `Rc`. This made `iceoryx2::service::Details` obsolete which was removed. …

[#100] rc owned management structs

---

iceoryx2-bb/lock-free/src/mpmc/container.rs
iceoryx2-bb/lock-free/tests/mpmc_container_tests.rs
iceoryx2-bb/posix/src/shared_memory.rs
iceoryx2-bb/posix/tests/shared_memory_tests.rs
iceoryx2-cal/src/dynamic_storage/mod.rs
iceoryx2-cal/src/dynamic_storage/posix_shared_memory.rs
iceoryx2-cal/src/dynamic_storage/process_local.rs
iceoryx2-cal/src/zero_copy_connection/posix_shared_memory.rs
iceoryx2-cal/tests/dynamic_storage_trait_tests.rs
iceoryx2/src/port/listener.rs
iceoryx2/src/port/notifier.rs
iceoryx2/src/port/publisher.rs
iceoryx2/src/port/subscriber.rs
iceoryx2/src/service/builder/event.rs
iceoryx2/src/service/builder/publish_subscribe.rs
iceoryx2/src/service/dynamic_config/event.rs
iceoryx2/src/service/dynamic_config/publish_subscribe.rs
iceoryx2/src/service/mod.rs
iceoryx2/src/service/port_factory/listener.rs
iceoryx2/src/service/port_factory/notifier.rs

* Refactored the `ContainerState` so that it no longer requires a reference to the corresponding `Container`. Removed one lifetime entanglement.
* Add non-RAII API to `Container`, removed another lifetime entanglement at the cost that values must be manually removed.
1. [x] Changelog updated [in the unreleased section][changelog] including API …

[#100] dynamic segment rc owned

---

doc/release-notes/iceoryx2-unreleased.md
iceoryx2/src/port/publisher.rs
iceoryx2/tests/service_publish_subscribe_tests.rs

The retrieve buffer can overflow when the publisher loans many samples and send them one by one without any more loans. The problem is, that the samples in the retrieve buffer are only recollected whenever a new loan is acquired. When we never have to call loan again since we have a big buffer of loaned samples on the publisher side, the retrieve buffer will overflow and the communication fails.
The solution is rather simple: Call `retrieve_returned_samples` before sending any new samples. In this way, we ensure that we reclaim all borrowed samples before we borrow (send) new samples to the receiver.
1. [x] Every source code file has a copyright header with …

[#116] Fix retrieve buffer overflow

---

doc/release-notes/iceoryx2-unreleased.md
iceoryx2-bb/posix/src/shared_memory.rs
iceoryx2-cal/src/zero_copy_connection/mod.rs
iceoryx2-cal/src/zero_copy_connection/posix_shared_memory.rs
iceoryx2-cal/src/zero_copy_connection/process_local.rs
iceoryx2-cal/tests/zero_copy_connection_trait_tests.rs
iceoryx2/src/port/publisher.rs

Fixes race in `posix::SharedMemory`.
1. Two processes try to create or open a shared memory
1. Both detect that none is available
2. Both try to create a new one - only one will succeed, the other complains: shm does not exist and I cannot create a new one.
Solution: If create fails, try to reopen it.
Removes: retrieve buffer full check from zero copy sender. The sender does not have enough information available to determine if the buffer is really insufficient. It needs to know how many samples the subscriber has currently borrowed - an information only the receiver has.
Introduce memory sync in zero copy connection open procedure. When a zero copy connection is opened and the creation is still in progress, the opener will check the `init_state` until it is initialized. If it is …

[#116] Fix race in shm create or open

---

iceoryx2/tests/publisher_tests.rs

This was fixed with #134, just to be sure, I introduced a watchdog for the test. If it is still deadlocking we know it after 10 seconds and not after the CI timeout.
1. [x] All checks …

[#11] Activate flaky windows test

---

Cargo.toml
doc/release-notes/iceoryx2-unreleased.md
iceoryx2-cal/src/shm_allocator/mod.rs
iceoryx2-cal/tests/shm_allocator_pool_allocator_tests.rs
iceoryx2/src/port/listener.rs
iceoryx2/src/port/notifier.rs
iceoryx2/src/port/publisher.rs
iceoryx2/src/port/subscriber.rs
iceoryx2/src/sample.rs
iceoryx2/src/service/builder/event.rs
iceoryx2/src/service/builder/mod.rs
iceoryx2/src/service/builder/publish_subscribe.rs
iceoryx2/tests/sample_mut_tests.rs
iceoryx2/tests/sample_tests.rs
iceoryx2/tests/service_event_tests.rs
iceoryx2/tests/service_publish_subscribe_tests.rs

[#133] write drop tests

---

doc/release-notes/iceoryx2-unreleased.md
examples/Cargo.toml
examples/README.md
examples/examples/complex_data_types/README.md
examples/examples/complex_data_types/complex_data_types.rs
examples/examples/event/README.md
examples/examples/publish_subscribe/README.md
iceoryx2-bb/container/src/byte_string.rs

[#175] example with complex data types

---

.github/workflows/build-test.yml
doc/release-notes/iceoryx2-unreleased.md
iceoryx2-bb/lock-free/tests/bitset_tests.rs
iceoryx2-bb/posix/src/unix_datagram_socket.rs
iceoryx2-cal/src/event/common.rs
iceoryx2-cal/src/event/mod.rs
iceoryx2-cal/src/event/process_local.rs
iceoryx2-cal/src/event/unix_datagram_socket.rs
iceoryx2-cal/tests/communication_channel_trait_tests.rs
iceoryx2-cal/tests/event_tests.rs
iceoryx2-pal/posix/src/windows/errno.rs
iceoryx2-pal/posix/src/windows/socket.rs
iceoryx2/src/port/details/publisher_connections.rs
iceoryx2/src/port/details/subscriber_connections.rs
iceoryx2/src/port/listener.rs
iceoryx2/src/port/notifier.rs
iceoryx2/src/port/publisher.rs
iceoryx2/src/port/subscriber.rs
iceoryx2/src/sample.rs
iceoryx2/src/sample_mut.rs
iceoryx2/src/service/builder/event.rs
iceoryx2/src/service/builder/mod.rs
iceoryx2/src/service/builder/publish_subscribe.rs
iceoryx2/src/service/mod.rs
iceoryx2/src/service/zero_copy.rs
iceoryx2/tests/service_event_tests.rs

[#139] fix event concurrency issues

---

README.md
benchmarks/publish-subscribe/src/main.rs
doc/release-notes/iceoryx2-unreleased.md
examples/examples/complex_data_types/complex_data_types.rs
examples/examples/publish_subscribe/publisher.rs
examples/examples/publish_subscribe/subscriber.rs
iceoryx2/src/config.rs
iceoryx2/src/lib.rs
iceoryx2/src/port/publisher.rs
iceoryx2/src/port/subscriber.rs
iceoryx2/src/port/update_connections.rs
iceoryx2/src/sample.rs
iceoryx2/src/sample_mut.rs
iceoryx2/src/service/builder/publish_subscribe.rs
iceoryx2/src/service/dynamic_config/publish_subscribe.rs
iceoryx2/src/service/header/publish_subscribe.rs
iceoryx2/src/service/mod.rs
iceoryx2/src/service/port_factory/publish_subscribe.rs
iceoryx2/src/service/port_factory/publisher.rs
iceoryx2/src/service/port_factory/subscriber.rs
iceoryx2/src/service/process_local.rs
iceoryx2/src/service/static_config/publish_subscribe.rs
iceoryx2/src/service/zero_copy.rs
iceoryx2/tests/publisher_tests.rs
iceoryx2/tests/sample_mut_tests.rs
iceoryx2/tests/sample_tests.rs
iceoryx2/tests/service_publish_subscribe_tests.rs
iceoryx2/tests/service_tests.rs

This PR prepares the API for the new untyped API by introducing `.typed::<T>()` in the pub/sub builder which returns a typed builder.
In the upcoming sliced and untyped API a similar method will be introduced called `.sliced::<T>()` or `.untyped()` that will return a sliced- or untyped-builder.
1. [x] …

[#195] add sliced api

---

README.md
iceoryx2-bb/posix/src/creation_mode.rs
iceoryx2-bb/posix/tests/access_mode_tests.rs
iceoryx2-bb/posix/tests/clock_tests.rs
iceoryx2-bb/posix/tests/condition_variable_tests.rs
iceoryx2-bb/posix/tests/creation_mode_tests.rs
iceoryx2-bb/posix/tests/directory_tests.rs
iceoryx2-bb/posix/tests/file_descriptor_set_tests.rs
iceoryx2-bb/posix/tests/file_lock_tests.rs
iceoryx2-bb/posix/tests/file_tests.rs
iceoryx2-bb/posix/tests/file_type_tests.rs
iceoryx2-bb/posix/tests/group_tests.rs
iceoryx2-bb/posix/tests/memory_lock_tests.rs
iceoryx2-pal/posix/src/windows/fcntl.rs
iceoryx2-pal/posix/src/windows/mman.rs
iceoryx2-pal/posix/src/windows/unistd.rs
iceoryx2-pal/posix/src/windows/win32_handle_translator.rs

[#213] Add further tests

---

iceoryx2-bb/container/src/byte_string.rs
iceoryx2-bb/container/src/semantic_string.rs
iceoryx2-bb/container/tests/byte_string_tests.rs
iceoryx2-bb/container/tests/queue_tests.rs
iceoryx2-bb/posix/src/directory.rs
iceoryx2-bb/posix/src/group.rs
iceoryx2-bb/trait-tests/tests/relocatable_container_tests.rs
iceoryx2-bb/trait-tests/tests/semantic_string_tests.rs

[#213] increase test container coverage

---

.cirrus.yml

On Cirrus-CI the test tasks are build with different flags than the build tasks. This results in rebuilding everything for the tests and increases the CI time quite a lot for the aarch64 release builds.
This PR sets the `RUSTFLAGS` in a global environment variable, similar to the github actions.
1. [x] …

[#3] Set 'RUSTFLAGS' as global env variable on cirrus ci

---

Cargo.toml
doc/release-notes/iceoryx2-unreleased.md
iceoryx2-cli/iox2-introspect/Cargo.toml
iceoryx2-cli/iox2-introspect/src/main.rs
iceoryx2-cli/iox2-processes/Cargo.toml
iceoryx2-cli/iox2-processes/src/main.rs
iceoryx2-cli/iox2-pub/Cargo.toml
iceoryx2-cli/iox2-pub/src/main.rs
iceoryx2-cli/iox2-rpc/Cargo.toml
iceoryx2-cli/iox2-rpc/src/main.rs
iceoryx2-cli/iox2-services/Cargo.toml
iceoryx2-cli/iox2-services/src/main.rs
iceoryx2-cli/iox2-sub/Cargo.toml
iceoryx2-cli/iox2-sub/src/main.rs
iceoryx2-cli/iox2/Cargo.toml
iceoryx2-cli/iox2/src/cli.rs
iceoryx2-cli/iox2/src/commands.rs
iceoryx2-cli/iox2/src/main.rs

1. Adds the top-level entry-point CLI for `iox2`
```
$ ./target/debug/iox2 --help
```
1. The top level CLI discovers available commands by looking for binaries with the prefix `iox2-` in the `$PATH` or in the cargo build directories
1. Binaries that are discovered can be viewed using `--list` - the same as how `cargo` handles external binaries
```
$ ./target/debug/iox2 --list
```
1. The locations checked for binaries can be viewed using:
```
$ ./target/debug/iox2 --paths
```
1. Discovered binaries in `PATH`  can be executed as if they were a defined sub command
```
$ ./target/debug/iox2 services
```
1. Discovered binaries in cargo build directories can only be executed with the flag `--dev` set
```
$ ./target/debug/iox2 --dev services
```
1. This distinction is to deal with the case where …

[#98] Add entrypoint for iox2 cli

---

iceoryx2-pal/posix/build.rs
iceoryx2-pal/posix/src/c/dirent.c
iceoryx2-pal/posix/src/macos/dirent.rs

Forwards calls to `dirent` to C macro defined on macOS platform.
Only required on macOS as `dirent` is declared as a function on other platforms.
[eca]: …

[#266] Configure bindgen to bind dirfd C macro on macOS

---

iceoryx2-bb/testing/src/assert.rs
iceoryx2-bb/testing/src/lib.rs
iceoryx2/src/node/mod.rs
iceoryx2/tests/node_death_tests.rs
iceoryx2/tests/node_tests.rs

The bug is fixed, but it no longer works to stage a death of a node but this is only required for resource cleanup tests. For now, the test is ignored. Soon I will start with the resource cleanup implementation where I need to find a solution for the problem and fix it.
1. [x] Changelog updated [in the …

[#274] Node is detected as alive when it comes from its own process

---

iceoryx2-ffi/ffi/README.md
iceoryx2-ffi/ffi/src/node.rs
iceoryx2-ffi/ffi/src/node_builder.rs
iceoryx2-ffi/ffi/src/node_name.rs

This PR crates the `NodeName` C API and introduces a new pattern for the type erasure which is better suited for moving the ownership.
1. [x] All checks have passed (except …

[#210] Create NodeName C API

---

examples/c/publish_subscribe/src/publisher.c
iceoryx2-ffi/ffi/README.md
iceoryx2-ffi/ffi/src/config.rs
iceoryx2-ffi/ffi/src/node.rs
iceoryx2-ffi/ffi/src/node_builder.rs
iceoryx2-ffi/ffi/src/node_name.rs
iceoryx2-ffi/ffi/src/service_builder.rs

This PR adjust the naming and structure for all the FFI files according the last PR …

[#210] Adjust naming convention and structuree in the remaining files

---

Cargo.toml
iceoryx2-ffi/ffi-macros/Cargo.toml
iceoryx2-ffi/ffi-macros/src/lib.rs
iceoryx2-ffi/ffi/Cargo.toml
iceoryx2-ffi/ffi/src/node.rs
iceoryx2-ffi/ffi/src/node_builder.rs
iceoryx2-ffi/ffi/src/node_name.rs

This PR adds a proc macro to reduce the amount of boilerplate code required for the FFI crate …

[#210] Add proc macro for FFI boilerplate code

---

iceoryx2-ffi/ffi/cbindgen.toml
iceoryx2-ffi/ffi/src/api/mod.rs
iceoryx2-ffi/ffi/src/api/node.rs
iceoryx2-ffi/ffi/src/api/service_builder.rs
iceoryx2-ffi/ffi/src/api/service_name.rs
iceoryx2-ffi/ffi/src/tests/mod.rs
iceoryx2-ffi/ffi/src/tests/service_name_tests.rs

This PR adds the `ServiceName` C API, which is basically a copy of the `NodeName` API …

[#210] Create ServiceName C API

---

iceoryx2/src/service/dynamic_config/event.rs
iceoryx2/src/service/dynamic_config/publish_subscribe.rs

[#350] Extend dynamic config API

---

iceoryx2-ffi/cxx/include/iox2/publisher.hpp
iceoryx2-ffi/cxx/include/iox2/sample.hpp
iceoryx2-ffi/cxx/include/iox2/sample_mut.hpp
iceoryx2-ffi/cxx/include/iox2/subscriber.hpp
iceoryx2-ffi/ffi/src/api/sample.rs
iceoryx2-ffi/ffi/src/api/sample_mut.rs

[#210] Make C sample movable

---

benchmarks/event/src/main.rs
benchmarks/publish-subscribe/src/main.rs
doc/release-notes/iceoryx2-unreleased.md
iceoryx2-cal/src/dynamic_storage/posix_shared_memory.rs
iceoryx2-cal/src/shared_memory/common.rs
iceoryx2-cal/src/static_storage/file.rs
iceoryx2-cal/src/static_storage/mod.rs
iceoryx2-cal/src/static_storage/process_local.rs
iceoryx2-cal/src/zero_copy_connection/common.rs
iceoryx2-cal/src/zero_copy_connection/mod.rs
iceoryx2-cal/tests/dynamic_storage_posix_shared_memory_tests.rs
iceoryx2-cal/tests/shared_memory_posix_shared_memory_tests.rs
iceoryx2-cal/tests/static_storage_file_tests.rs
iceoryx2-cal/tests/static_storage_trait_tests.rs
iceoryx2-cal/tests/zero_copy_connection_posix_shared_memory_tests.rs
iceoryx2/src/node/mod.rs
iceoryx2/src/port/details/publisher_connections.rs
iceoryx2/src/port/details/subscriber_connections.rs
iceoryx2/src/service/builder/event.rs
iceoryx2/src/service/builder/mod.rs
iceoryx2/src/service/builder/publish_subscribe.rs
iceoryx2/src/service/mod.rs

From previous PR:
How about calling this `cpu_core_participant_1` and `cpu_core_participant_2`. We could then use the same names for the multi-process benchmark.
In the PR we check if the version number is equal zero to additionally determine if the shared memory was initialized or not. Technically it is undefined behavior but works most of the time since the OS zero's the memory. A cleaner solution would be to apply the access rights strategy to the trampoline files but this will cost a lot of effort. Here is the tracking issue for that: https://github.com/eclipse-iceoryx/iceoryx2/issues/364
In this PR I would pursue the version flag approach since it offers a solution and pursue the #364 later.
1. [x] PR title is short, expressive and …

[#361] creation timeout

---

examples/Cargo.toml
examples/README.md
examples/rust/domains/README.md
examples/rust/domains/discovery.rs
examples/rust/domains/publisher.rs
examples/rust/domains/subscriber.rs

* example that demonstrates how to create iceoryx2 groups/domains that are isolated …

[#370] domain separation example

---

Cargo.toml
iceoryx2-cli/iox2-nodes/Cargo.toml
iceoryx2-cli/iox2-nodes/src/cli.rs
iceoryx2-cli/iox2-nodes/src/commands.rs
iceoryx2-cli/iox2-nodes/src/filter.rs
iceoryx2-cli/iox2-nodes/src/main.rs
iceoryx2-cli/iox2-services/Cargo.toml
iceoryx2-cli/iox2-services/src/cli.rs
iceoryx2-cli/iox2-services/src/commands.rs
iceoryx2-cli/iox2-services/src/filter.rs
iceoryx2-cli/iox2-services/src/main.rs
iceoryx2-cli/iox2/src/cli.rs
iceoryx2-cli/iox2/src/main.rs
iceoryx2-cli/utils/Cargo.toml
iceoryx2-cli/utils/src/lib.rs
iceoryx2-cli/utils/src/output.rs

1. enables commands `iox2 nodes list` and `iox2 nodes details`
1. node ids are represented as hex rather than separate elements (pid, timestamps, counter)
1. to retrieve node details, node id (as hex), node name, or pid can be provided
1. if there are multiple nodes matching, all nodes should be provided
1. output can be filtered by node state (Alive, Dead, etc.)
1. functionality for outputting in multiple formats has been inherited (RON, JSON, YAML)
3. cleanliness tweaks across all cli
1. made implementations consistent
3. reused output structs across clis
**Usage:**
<details>
<summary>iox2-nodes</summary>
```bash
$ iox2-nodes --help
Query information about iceoryx2 nodes
Usage: iox2-nodes [OPTIONS] [COMMAND]
Options:
-f, --format <FORMAT>  [default: RON] [possible values: RON, JSON, …
```

[#98] add `iox2 nodes` cli 

---

.github/ISSUE_TEMPLATE/bug_report.md
FAQ.md
doc/release-notes/iceoryx2-unreleased.md
iceoryx2-bb/log/src/lib.rs
iceoryx2/src/prelude.rs

Sets default log level to `LogLevel:Warn`. …

[#392] noisy logger

---

README.md
doc/release-notes/iceoryx2-unreleased.md

Adding self to contributors.
1. [ ] ~~Every source code file has a copyright header with `SPDX-License-Identifier: Apache-2.0 OR MIT`~~
1. [ ] ~~Tests follow the [best practice for testing][testing]~~
1. [ ] ~~Changelog updated [in the unreleased section][changelog] including API breaking changes~~
[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messa …

[#4] Update contributors

---

FAQ.md
doc/release-notes/iceoryx2-unreleased.md
iceoryx2-pal/concurrency-sync/Cargo.toml
iceoryx2-pal/concurrency-sync/src/iox_atomic.rs
iceoryx2/Cargo.toml
iceoryx2/src/lib.rs

This PR enables lock-free atomics for 32-bit architectures. Since all common 32-bit architectures support 8 byte CAS operations, the reader-writer lock implementation is not required. …

[#401] Lock-free Atomics for 32-bit architectures

---

iceoryx2-ffi/cxx/src/node_name.cpp
iceoryx2-ffi/cxx/src/service_name.cpp
iceoryx2-ffi/ffi/src/api/node_name.rs
iceoryx2-ffi/ffi/src/api/service_name.rs
iceoryx2-ffi/ffi/src/tests/node_name_tests.rs
iceoryx2-ffi/ffi/src/tests/node_tests.rs
iceoryx2-ffi/ffi/src/tests/service_name_tests.rs

The node and service name C-API pretent to return a null terminated C-style string. This is not the case though, since the Rust `NodeName` and `ServiceName` is based on a Rust `String` and not on an iceoryx2 `SemanticString`.
This PR fixes the documentation and makes passing a pointer for the string length mandatory.
1. [x] Tests follow the [best practice for …

[#210] Fix node and service name C API

---

ROADMAP.md

[#4] Update roadmap

---

doc/release-notes/iceoryx2-v0.4.1.md
iceoryx2-cli/iox2/src/commands.rs

1. The CLI was incorrectly assuming it would always be called from a cargo workspace
2. With this change, the CLI will ignore build paths and only try to find commands in the install path
1. [ ] ~~Tests follow the [best practice for testing][testing]~~
1. [x] Assign PR to …

[#409] Fix bug in iox2 when called outside of cargo workspace

---

iceoryx2/src/node/mod.rs
iceoryx2/src/port/notifier.rs
iceoryx2/src/port/publisher.rs
iceoryx2/src/port/subscriber.rs

This change is done by calling `cargo clippy --fix --lib -p iceoryx2`
I'm still learning about the code of iceoryx2, so I tried to improve some of them(trivial but nice to have) during the process. 
1. [X] Add sensible notes for the reviewer
1. [X] PR title is short, expressive and meaningful
1. [X] Relevant issues are linked in the [References](#references) section
1. [X] Every source code file has a copyright header with `SPDX-License-Identifier: Apache-2.0 OR MIT`
1. [X] Branch follows the naming format (`iox2-123-introduce-posix-ipc-example`)
1. [X] Commits messages are according to this [guideline][commit-guidelines]
1. [X] Tests follow the [best practice for testing][testing]
1. [X] Changelog updated [in the unreleased section][changelog] including API breaking changes
1. [x] Assign …

[#430] Fix clippy single match warning in package iceoryx2

---

.github/workflows/miri-check.yml
.miri_allowlist
internal/scripts/ci_run_miri.sh

Allow CI failures for now
I have integrated miri in github action while supporting a shell-style `.miri_allowlist` file for all sub-folders to run `cargo miri test`. 
1. [X] Add sensible notes for the reviewer
1. [X] PR title is short, expressive and meaningful
1. [X] Relevant issues are linked in the [References](#references) section
1. [X] Every source code file has a copyright header with `SPDX-License-Identifier: Apache-2.0 OR MIT`
1. [X] Branch follows the naming format (`iox2-123-introduce-posix-ipc-example`)
1. [X] Commits messages are according to this [guideline][commit-guidelines]
1. [X] Tests follow the [best practice for testing][testing]
1. [X] Changelog updated [in the unreleased section][changelog] including API breaking changes
1. [X] All …

[#60] integrate miri in ci with an allow list

---

doc/release-notes/iceoryx2-unreleased.md
iceoryx2/src/config.rs

This PR fixes a misleading warning related to the default config file. If the file was not found in the first place, only a debug message is printed. Only when the file is found and could not be processed, the warning is printed.
See related issue for more information.
1. [x] Changelog updated [in the …

[#437] Fix misleading warning related to default config file

---

FAQ.md
examples/README.md

[#436] Document payload type restrictions

---

iceoryx2-bb/posix/src/signal.rs
iceoryx2-bb/posix/tests/signal_tests.rs

The `SignalHandler` registers in the beginning every signal to keep track of them so that the user can later acquire them via an internal atomic variable. The problem is, that by default it also registers `SIGSEGV` and other fatal signals. If such a signal is emitted in turns into an infinite loop where the signal callback is called.
This can be mitigated by splitting up the FetchableSignals into FatalFetchableSignals (e.g. `SIGSEGV`, ...) and NonFatalFetchableSignals (`SIGINT`, `SIGUSR1` ... ).
Certain operations are only allowed for NonFatalFetchableSignals, like acquiring the last signal that was emitted. Also the SignalHandler only registers NonFatalFetchableSignals by default so that the user can later acquire the signal that was emitted. For FatalFetchableSignals it would not make …

[#436] Split up the sig handler into non fatal and fatal signals

---

iceoryx2/src/service/builder/publish_subscribe.rs
iceoryx2/src/service/static_config/message_type_details.rs
iceoryx2/tests/service_static_config_tests.rs

I have added some test cases during I'm learning the codes. It improves out test.
1. [X] Add sensible notes for the reviewer
1. [X] PR title is short, expressive and meaningful
1. [X] Relevant issues are linked in the [References](#references) section
1. [X] Every source code file has a copyright header with `SPDX-License-Identifier: Apache-2.0 OR MIT`
1. [X] Branch follows the naming format (`iox2-123-introduce-posix-ipc-example`)
1. [X] Commits messages are according to this [guideline][commit-guidelines]
1. [X] Tests follow the [best practice for testing][testing]
1. [X] Changelog updated [in the unreleased section][changelog] including API breaking changes …

[#213] test: add test cases

---

iceoryx2/src/service/static_config/message_type_details.rs
iceoryx2/src/service/static_config/messaging_pattern.rs

- [] Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed) …

 [#213]: tests methods of MessageTypeDetails

---

iceoryx2-bb/log/src/logger/file.rs
iceoryx2-bb/log/src/logger/mod.rs

Implements a simple file logger that does not use any additional crates and where we can add a simple C/C++ binding for it to be able to exchange loggers from different languages.
1. …

[#464] file logger

---

examples/rust/publish_subscribe/publisher.rs
internal/cpp_doc_generator/developer_guide.rst
internal/cpp_doc_generator/developer_guide_logging.rst
internal/cpp_doc_generator/index.rst

A detailed documentation about logging (and also how to handle errors since they are tightly coupled to logging) in iceoryx2.
1. [x] All checks have passed (except …

[#4] Introduce developer guide with log documentation

---

.github/workflows/build-test.yml
iceoryx2-bb/log/src/lib.rs
iceoryx2-bb/log/src/logger/buffer.rs
iceoryx2-bb/log/src/logger/console.rs
iceoryx2-bb/log/src/logger/file.rs
iceoryx2-bb/log/src/logger/log.rs
iceoryx2-bb/log/src/logger/mod.rs
iceoryx2-bb/log/src/logger/tracing.rs
iceoryx2-ffi/cxx/include/iox2/enum_translation.hpp
iceoryx2-ffi/cxx/include/iox2/log.hpp
iceoryx2-ffi/cxx/include/iox2/log_level.hpp
iceoryx2-ffi/cxx/src/log.cpp
iceoryx2-ffi/cxx/tests/src/log.cpp
iceoryx2-ffi/cxx/tests/src/log_tests.cpp
iceoryx2-ffi/ffi/src/api/log.rs

* Implements the C and C++ binding for `log`.
* It renames the `Logger` trait for custom loggers to `Log` to be more in line with the Rust naming scheme - traits are verbs
* provides user convenience functions to set the file logger as default logger
1. [x] Changelog updated [in the unreleased …

[#464] c api

---

doc/how-to-create-an-iceoryx2-release.md
iceoryx2-bb/elementary/src/package_version.rs
iceoryx2-bb/elementary/tests/package_version_tests.rs
iceoryx2-cal/src/dynamic_storage/posix_shared_memory.rs
iceoryx2-ffi/cxx/tests/src/service_event_tests.cpp
iceoryx2-ffi/cxx/tests/src/service_publish_subscribe_tests.cpp
iceoryx2-ffi/cxx/tests/src/test.hpp
iceoryx2-ffi/cxx/tests/src/unique_port_id_tests.cpp

Fixes some parts of the problem but not everything …

[#349] Add service name generator to be able to run tests concurrently

---

.cirrus.yml
.github/workflows/build-test.yml
BUILD.bazel
FAQ_ICEORYX_DEVS.md
doc/bazel/README.md
iceoryx2-bb/lock-free/tests/bitset_tests.rs
iceoryx2-bb/log/BUILD.bazel
iceoryx2-bb/posix/BUILD.bazel
iceoryx2-bb/posix/tests/ipc_capable_trait_tests.rs
iceoryx2-bb/posix/tests/semaphore_tests.rs
iceoryx2-cal/BUILD.bazel
iceoryx2-ffi/cxx/include/iox2/enum_translation.hpp
iceoryx2-pal/posix/BUILD.bazel
iceoryx2/BUILD.bazel
internal/scripts/ci_build_and_test_freebsd.sh
internal/scripts/generate-cov-report.sh

This PR adds remaining cargo feature flags to bazel.
Additionally, it re-enables running the tests via bazel in the CI and optimizes the CI to not partially rebuild the code for tests by harmonizing the flags passed to `cargo build` and `cargo nextest run`
Due to reaching the Cirrus CI limit early this month, the Cirrus CI is deactivated and the targets are limited even further.
Finally, a FAQ for iceoryx developers was added.
1. [x] Commits …

[#349] Add remaining cargo feature flags to bazel

---

benchmarks/publish-subscribe/src/main.rs
doc/release-notes/iceoryx2-unreleased.md

The benchmark did not consider memory operations. It was true zero copy, meaning that the user used the API so that the data is directly produced into the shared memory and then sent. With the `--send-copy` flag the memory is zero'ed under the hood so that it simulates some memory operations.
1. [x] …

[#483] Add --send-copy flag to pub/sub benchmark

---

iceoryx2-ffi/cxx/include/iox2/waitset.hpp
iceoryx2-ffi/cxx/include/iox2/waitset_hash.hpp
iceoryx2-ffi/cxx/src/waitset.cpp
iceoryx2-ffi/ffi/src/api/waitset_attachment_id.rs
iceoryx2/src/port/waitset.rs

To be able to perform better debugging, the streaming operator for the waitset attachment id was added. Furthermore, `std::hash` was implemented for it to be able to organize it in a hash map.
1. [x] Assign PR to …

[#488] waitset attachment id improvements

---

doc/release-notes/iceoryx2-unreleased.md
iceoryx2-bb/posix/tests/unix_datagram_socket_tests.rs
iceoryx2-ffi/cxx/include/iox2/header_publish_subscribe.hpp
iceoryx2-ffi/cxx/src/header_publish_subscribe.cpp
iceoryx2-ffi/ffi/src/api/publish_subscribe_header.rs
iceoryx2-ffi/ffi/src/api/publisher.rs
iceoryx2-ffi/ffi/src/api/service_builder.rs
iceoryx2-ffi/ffi/src/api/subscriber.rs
iceoryx2/src/port/publisher.rs
iceoryx2/src/port/subscriber.rs
iceoryx2/src/sample_mut_uninit.rs
iceoryx2/src/service/builder/publish_subscribe.rs
iceoryx2/src/service/header/publish_subscribe.rs
iceoryx2/src/service/static_config/message_type_details.rs
iceoryx2/tests/publisher_tests.rs
iceoryx2/tests/service_publish_subscribe_tests.rs
iceoryx2/tests/subscriber_tests.rs

In this PR the API used when overriding the `MessageTypeDetails` is strictly separated from the end user API.
* When overriding the `MessageTypeDetails` you must use `[CustomPayloadMarker]` as message type
* You can only loan samples via `Publisher::loan_custom_payload()`
* You can only receive samples via `Subscriber::receive_custom_payload()`.
The reason is, that in those cases the `Sample` and `SampleMut` handle the data a bit different. When calling `Publisher::loan_custom_payload(123)` and 123 corresponds to the number of elements, this number is stored in the samples header but `Sample::payload().len()` will return `123 * MessageTypeDetails::payload.size`, the bytes used by the sample. When the `MessageTypeDetails::payload.size` is not overridden, `Sample::payload().len() == …

[#498] cleanup message type details

---

doc/release-notes/iceoryx2-unreleased.md
examples/c/domains/src/publisher.c
examples/c/publish_subscribe/src/publisher.c
examples/c/publish_subscribe_with_user_header/src/publisher.c
examples/cxx/publish_subscribe_dynamic_data/src/publisher.cpp
examples/cxx/publish_subscribe_dynamic_data/src/subscriber.cpp
examples/rust/publish_subscribe_dynamic_data/publisher.rs
iceoryx2-ffi/cxx/include/iox/slice.hpp
iceoryx2-ffi/cxx/include/iox2/payload_info.hpp
iceoryx2-ffi/cxx/include/iox2/port_factory_publisher.hpp
iceoryx2-ffi/cxx/include/iox2/publisher.hpp
iceoryx2-ffi/cxx/include/iox2/sample.hpp
iceoryx2-ffi/cxx/include/iox2/sample_mut.hpp
iceoryx2-ffi/cxx/include/iox2/sample_mut_uninit.hpp
iceoryx2-ffi/cxx/include/iox2/service_builder_publish_subscribe.hpp
iceoryx2-ffi/cxx/tests/src/service_publish_subscribe_tests.cpp
iceoryx2-ffi/cxx/tests/src/slice_tests.cpp
iceoryx2-ffi/ffi/src/api/port_factory_publisher_builder.rs
iceoryx2-ffi/ffi/src/api/publisher.rs
iceoryx2-ffi/ffi/src/api/sample.rs
iceoryx2-ffi/ffi/src/api/sample_mut.rs
iceoryx2-ffi/ffi/src/api/service_builder_pub_sub.rs
iceoryx2/src/port/publisher.rs

1. Implement `iox::Slice`
2. Implement `loan_slice` APIs in C++ binding
3. Expose properties `payload_alignment` and `max_slice_len` in C++ binding
1. [x] All checks have passed …

[#490] Enable loan_slice APIs in CXX bindings

---

examples/c/event_multiplexing/src/wait.c
examples/cxx/event_multiplexing/src/wait.cpp
examples/rust/event_multiplexing/wait.rs
iceoryx2-bb/posix/src/deadline_queue.rs
iceoryx2-bb/posix/tests/deadline_queue_tests.rs
iceoryx2-ffi/cxx/include/iox2/enum_translation.hpp
iceoryx2-ffi/cxx/include/iox2/waitset.hpp
iceoryx2-ffi/cxx/include/iox2/waitset_enums.hpp
iceoryx2-ffi/cxx/src/waitset.cpp
iceoryx2-ffi/cxx/tests/src/waitset_tests.cpp
iceoryx2-ffi/ffi/src/api/waitset.rs
iceoryx2-ffi/ffi/src/api/waitset_attachment_id.rs
iceoryx2/src/port/waitset.rs
iceoryx2/tests/waitset_tests.rs

* `DeadlineQueue::missed_deadlines()` callback needs to return `CallbackProgression` so that the user is able to stop handling missed deadlines when required.
* `WaitSet::try_wait_and_process` was renamed to `WaitSet::wait_and_process_once` since the function was actually blocking in contrast what the name suggested with the `try_` prefix
* behavior adjusted, blocks until the first event arrives, then handles all events and returns, to make it usable in external event loops.
* `WaitSet::wait_and_process` and `WaitSet::wait_and_process_once` callbacks need to return `CallbackProgression` to terminate event handling whenever required - this replaces the buggy `WaitSet::stop()` call.
1. [x] …

[#507] waitset adjustments

---

doc/release-notes/iceoryx2-unreleased.md
iceoryx2-ffi/cxx/include/iox2/port_factory_publisher.hpp

The `max_slice_len` builder option is available for `Publisher`s that have a non-slice payload which is an API-Bug. This PR makes `max_slice_len` available only to `Publisher`s of payload `iox::Slice<T>`
1. [x] …

[#496] disable slice specific builder methods

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/build-test.yml

This PR adds another check to skip the CI if the PR has draft status. …

[#3] Skip CI if PR title starts with 'WIP'

---

benchmarks/queue/src/main.rs
iceoryx2-bb/container/src/queue.rs
iceoryx2-bb/container/src/slotmap.rs
iceoryx2-bb/container/src/vec.rs
iceoryx2-bb/lock-free/src/mpmc/bit_set.rs
iceoryx2-bb/lock-free/src/mpmc/container.rs
iceoryx2-bb/lock-free/src/mpmc/unique_index_set.rs
iceoryx2-bb/lock-free/src/spsc/index_queue.rs
iceoryx2-bb/lock-free/src/spsc/safely_overflowing_index_queue.rs
iceoryx2-bb/lock-free/tests/spsc_index_queue_tests.rs
iceoryx2-bb/lock-free/tests/spsc_safely_overflowing_index_queue_tests.rs
iceoryx2-cal/src/communication_channel/posix_shared_memory.rs
iceoryx2-cal/src/communication_channel/process_local.rs
iceoryx2-cal/src/dynamic_storage/mod.rs
iceoryx2-cal/src/dynamic_storage/posix_shared_memory.rs
iceoryx2-cal/src/shared_memory/mod.rs
iceoryx2-cal/src/shm_allocator/pointer_offset.rs
iceoryx2-cal/src/zero_copy_connection/common.rs
iceoryx2-cal/src/zero_copy_connection/mod.rs
iceoryx2-cal/tests/communication_channel_trait_tests.rs
iceoryx2-cal/tests/zero_copy_connection_posix_shared_memory_tests.rs
iceoryx2-cal/tests/zero_copy_connection_trait_tests.rs
iceoryx2/src/port/details/publisher_connections.rs
iceoryx2/src/port/details/subscriber_connections.rs
iceoryx2/tests/service_tests.rs
internal/scripts/iceoryx2_env.sh

Makes the ZeroCopyConnection concept multi segment capable. Instead of using of UsedChunkList, that tracks all outgoing samples to recover them when a subscriber dies, we have now one UsedChunkList per segment.
The user can define how many segments at most the ZeroCopyConnection can manage in parallel. This is useful to avoid the overhead in the case that one has a static type and not the slice case as payload.
1. [x] Commits messages are …

[#525] resizable shm support

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/build-test.yml
.github/workflows/miri-check.yml

The handling of draft PR is improved and the CI is fully skipped instead of resulting in a failure, which spams the github notifications.
Additionally, with this change, it is sufficient to set a PR to `Ready for review` in order to trigger the CI instead of having to do a dummy push.
Finally, the line breaks in bullet lists are also visible in the rendered markdown. Therefore the line limitation is suppressed for the PR template.
* Set the PR to a draft status, e.g. by the `Convert to draft` link, to indicate
that the work is not yet ready for review
* Once the PR is ready for review, press the `Ready for Review` button and push
a final commit to trigger the CI
`SPDX-License-Identifier: Apache-2.0 OR MIT`
breaking changes …

[#3] Trigger CI when a PR changes from draft to ready

---

iceoryx2-bb/posix/src/deadline_queue.rs
iceoryx2-bb/posix/tests/deadline_queue_tests.rs
iceoryx2/src/port/waitset.rs

Adds functionality to process all callbacks without waiting when providing a 0 `timeout`. …

[#533] Process callbacks in `deadline_queue` immediately on zero-timeout

---

.github/workflows/build-test.yml
CMakeLists.txt
doc/release-notes/iceoryx2-unreleased.md
iceoryx2-ffi/c/CMakeLists.txt
iceoryx2-ffi/c/README.md
iceoryx2-ffi/cxx/README.md
iceoryx2-ffi/cxx/cmake/fetch-iceoryx-hoofs.cmake

This PR adds a cmake option to use existing artifacts of the iceoryx2 cargo build.
The documentation is also updated and the CI uses this new mechanism to speed up the builds.
Closes #599

[#559] Reuse existing cargo build for C and C++ bindings

---

.cirrus.yml
Cargo.lock
Cargo.toml
internal/docker/ubuntu-22.04

This PR re-enables the Cirrus CI and introduces the same handling for draft PRs like the github CI. Unfortunately, a dummy commit is required to trigger the Cirrus CI after the PR is marked ready for review.
Additionally, a the 'hashbrown' dependency was updated to fix a security vulnerability and 'cbindgen' was updated to get rid of the unmaintained 'atty' dependency.
Relates to #3

[#3] Enable Cirrus CI

---

Cargo.lock
iceoryx2-bb/derive-macros/Cargo.toml
iceoryx2-bb/derive-macros/src/lib.rs
iceoryx2-bb/elementary/src/as_cstr.rs
iceoryx2-bb/elementary/src/as_string_literal.rs
iceoryx2-bb/elementary/src/lib.rs
iceoryx2-bb/testing/src/assert.rs
iceoryx2-ffi/ffi-macros/Cargo.toml
iceoryx2-ffi/ffi-macros/src/lib.rs
iceoryx2-ffi/ffi/src/api/config.rs
iceoryx2-ffi/ffi/src/api/listener.rs
iceoryx2-ffi/ffi/src/api/mod.rs
iceoryx2-ffi/ffi/src/api/node.rs
iceoryx2-ffi/ffi/src/api/node_builder.rs
iceoryx2-ffi/ffi/src/api/notifier.rs
iceoryx2-ffi/ffi/src/api/port_factory_listener_builder.rs
iceoryx2-ffi/ffi/src/api/port_factory_notifier_builder.rs
iceoryx2-ffi/ffi/src/api/port_factory_publisher_builder.rs
iceoryx2-ffi/ffi/src/api/port_factory_subscriber_builder.rs
iceoryx2-ffi/ffi/src/api/publisher.rs
iceoryx2-ffi/ffi/src/api/service.rs
iceoryx2-ffi/ffi/src/api/service_builder_event.rs
iceoryx2-ffi/ffi/src/api/service_builder_pub_sub.rs
iceoryx2-ffi/ffi/src/api/subscriber.rs
iceoryx2-ffi/ffi/src/api/waitset.rs

Fix bug where string literals were not null terminated and clean up implementation:
1. The trait and macro were renamed (trying to be more precise):
1. Trait: `AsCStr` which provides `as_const_cstr()` method, const alluding to the fact it is in `.rodata`
2. Macro: `CStrRepr` so `#[derive(CStrRepr)]` reads more naturally
1. The trait explicitly returns the `CStr` type
1. The test now properly asserts the generated strings are valid c strings:
```
assert_eq!(v1.as_const_cstr(), c"custom variant one");
assert_eq!(v2.as_const_cstr(), c"variant two");
```
1. Move `CStrRepr` macro into `iceoryx2-ffi-macros` since it is only used by `iceoryx2-ffi`
Unrelated: Also fix typo in existing `assert_that` message.
1. [x] PR title is short, expressive and …

[#491] Ensure enum string literals are null terminated

---

examples/cxx/event_based_communication/src/custom_subscriber.hpp

Inconsistent history requirements lead to a connection failure when the subscriber was created first.
Closes #566

[#566] Fix event based comm cxx example

---

doc/release-notes/iceoryx2-unreleased.md
iceoryx2-ffi/cxx/include/iox2/enum_translation.hpp
iceoryx2-ffi/cxx/include/iox2/node_failure_enums.hpp
iceoryx2-ffi/ffi/src/api/node.rs
iceoryx2/src/node/mod.rs
iceoryx2/src/service/builder/event.rs
iceoryx2/src/service/builder/publish_subscribe.rs
iceoryx2/src/service/mod.rs
iceoryx2/src/service/naming_scheme.rs

Shared Memory is not persistent in Windows. Whenever the last process that holds a shared memory handle terminates or crashes Windows removes the memory-mapped file from the file system. When a new process starts, it detects that there seems to exist the service but the dynamic segment of the service is missing - since the last process holding it crashed. So, it is correctly identified as corrupted, and the cleanup aborts here.
The solution is, when the node cleans up all stale resources and identifies a service as corrupted it deletes the static service config so that the service is removed completely.
In Windows we have to also handle the shm state file - which stores the shared memory size. So whenever a new shared memory is created and the state file already exists but the …

[#458] corrupted services cleanup

---

doc/release-notes/iceoryx2-unreleased.md
iceoryx2-pal/posix/src/windows/mman.rs

On Windows we have to create additional shm state files to track the size of the shared memory. When a process dies, those files keep living - but the shared memory is removed by the OS. So when another instance wants to create a shared memory with the same name, then it thinks it already exists since the stale state file is still around.
With this adjustments, the state file create function checks if the shm is actually present, if not, it deletes the old state file and creates a new one which fixes the issue.
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/concepts/best-practic …

[#458] cleanup stale windows shm state files

---

doc/release-notes/iceoryx2-unreleased.md
iceoryx2-bb/posix/src/socket_pair.rs
iceoryx2-bb/posix/tests/socket_pair_tests.rs
iceoryx2-cal/src/dynamic_storage/process_local.rs
iceoryx2-cal/src/event/mod.rs
iceoryx2-cal/src/event/process_local_socketpair.rs
iceoryx2-cal/tests/event_tests.rs
iceoryx2-pal/posix/src/windows/fcntl.rs
iceoryx2-pal/posix/src/windows/unistd.rs
iceoryx2/src/port/notifier.rs

Implemented the process local variant of events using socketpairs. Required - otherwise we do not have a real process local event variant, currently we use unix domain sockets with a file representation.
Windows required also a `dup` implementation on the platform since the notifier socket is acquired by duplicating one of the sockets from the socket pair since an event concept on that level is a M:1 connection (many notifiers and one listener) but a socketpair creates just 2 sockets. …

[#508] event concept based on socketpair

---

doc/release-notes/iceoryx2-unreleased.md
iceoryx2-bb/posix/src/signal.rs
iceoryx2-pal/posix/src/freebsd/constants.rs
iceoryx2-pal/posix/src/linux/constants.rs
iceoryx2-pal/posix/src/macos/constants.rs
iceoryx2-pal/posix/src/windows/constants.rs

[#605] remove sigpoll

---

doc/release-notes/iceoryx2-unreleased.md
iceoryx2-bb/log/src/lib.rs
iceoryx2-bb/log/src/logger/console.rs
iceoryx2-ffi/cxx/tests/src/log_tests.cpp

Fix the issue where the logger forwarded log messages to the custom logger that should have been filtered away by the log level.
Closes #608

[#608] fix log level

---

FAQ.md
benchmarks/README.md
benchmarks/event/src/main.rs
benchmarks/publish-subscribe/src/main.rs
doc/release-notes/iceoryx2-unreleased.md

The user shall be able to utilize our benchmarks to test more complex setups. For instance sending a message from a publisher with N subscribers or notify N listeners. The benchmarks were extended to support this use case.
Closes #610

[#610] extend benchmarks

---

iceoryx2-bb/lock-free/src/mpmc/unique_index_set.rs
iceoryx2-cal/src/shm_allocator/pointer_offset.rs
iceoryx2-pal/posix/src/macos/inet.rs
iceoryx2-pal/posix/src/windows/socket.rs

[#3] Fix CI for new rust 1.85

---

.github/workflows/build-test.yml
internal/scripts/ci_check_markdown_linting.sh

Removes automatic line correction from markdown linting script because it was occasionally breaking markdown formatting.
Also renamed the script to match the convention of other CI scripts: `check_markdown_linting.sh` -> `ci_check_markdown_linting.sh`
Closes #637

[#637] Remove line-length correction from markdown linting script

---

doc/release-notes/iceoryx2-unreleased.md
iceoryx2-bb/container/src/vec.rs

Changed to use internal slice impl that does
.cast() on ptr instead creating temporary reference that is then cases into ptr again. This causes miri to go crazy and think borrow stack is broken.
Closes #682

[#682] Fix miri borrow checker for MetaVec

---

iceoryx2-ffi/ffi/src/api/service_builder.rs
iceoryx2/src/active_request.rs
iceoryx2/src/pending_response.rs
iceoryx2/src/port/client.rs
iceoryx2/src/port/publisher.rs
iceoryx2/src/port/server.rs
iceoryx2/src/port/subscriber.rs
iceoryx2/src/raw_sample.rs
iceoryx2/src/request_mut.rs
iceoryx2/src/request_mut_uninit.rs
iceoryx2/src/response.rs
iceoryx2/src/response_mut.rs
iceoryx2/src/response_mut_uninit.rs
iceoryx2/src/service/builder/mod.rs
iceoryx2/src/service/builder/publish_subscribe.rs
iceoryx2/src/service/builder/request_response.rs
iceoryx2/src/service/dynamic_config/request_response.rs
iceoryx2/src/service/header/publish_subscribe.rs
iceoryx2/src/service/header/request_response.rs
iceoryx2/src/service/port_factory/client.rs
iceoryx2/src/service/port_factory/request_response.rs
iceoryx2/src/service/port_factory/server.rs
iceoryx2/tests/client_tests.rs
iceoryx2/tests/publisher_tests.rs
iceoryx2/tests/service_publish_subscribe_tests.rs
iceoryx2/tests/service_request_response_builder_tests.rs
iceoryx2/tests/service_request_response_tests.rs
iceoryx2/tests/subscriber_tests.rs

[#690] slice api

---

.cargo/config.toml
FAQ_ICEORYX_DEVS.md
doc/release-notes/iceoryx2-unreleased.md

[#711] Do not set default log level trace in cargo

---

README.md
iceoryx2/src/lib.rs
iceoryx2/src/port/client.rs
iceoryx2/src/service/mod.rs
iceoryx2/src/service/port_factory/server.rs

[#687] additional examples in doc

---

doc/release-notes/iceoryx2-unreleased.md
iceoryx2/tests/service_tests.rs

[#739] Fix flaky windows test

---

iceoryx2-ffi/ffi/src/api/active_request.rs
iceoryx2-ffi/ffi/src/api/client.rs
iceoryx2-ffi/ffi/src/api/config.rs
iceoryx2-ffi/ffi/src/api/pending_response.rs
iceoryx2-ffi/ffi/src/api/port_factory_client_builder.rs
iceoryx2-ffi/ffi/src/api/port_factory_request_response.rs
iceoryx2-ffi/ffi/src/api/port_factory_server_builder.rs
iceoryx2-ffi/ffi/src/api/request_header.rs
iceoryx2-ffi/ffi/src/api/request_mut.rs
iceoryx2-ffi/ffi/src/api/response.rs
iceoryx2-ffi/ffi/src/api/response_header.rs
iceoryx2-ffi/ffi/src/api/response_mut.rs
iceoryx2-ffi/ffi/src/api/server.rs
iceoryx2-ffi/ffi/src/api/service_builder.rs
iceoryx2-ffi/ffi/src/api/service_builder_request_response.rs

[#689] Fix typos in doc

---

doc/release-notes/iceoryx2-unreleased.md
iceoryx2/src/port/notifier.rs
iceoryx2/tests/service_event_tests.rs

[#794] filter out self delivery

---

doc/release-notes/iceoryx2-unreleased.md
iceoryx2-bb/system-types/src/ipv4_address.rs
iceoryx2-bb/system-types/src/port.rs

Changes to make all system types implement `ZeroCopySend`.
Closes #732

[#732] Implement ZeroCopySend for remaining system types

---

iceoryx2-ffi/ffi/src/api/attribute_set.rs
iceoryx2-pal/posix/src/windows/win32_udp_port_to_uds_name.rs

Fixes these errors:
```
error: implicit autoref creates a reference to the dereference of a raw pointer
--> iceoryx2-ffi/ffi/src/api/attribute_set.rs:198:7
|
198 |     (&(*handle)[index] as *const Attribute).cast()
|       ^^------^^^^^^^^
|         |
|         this raw pointer has type `*const AttributeSet`
|
= note: creating a reference requires the pointer target to be valid and imposes aliasing requirements
= note: references are created through calls to explicit `Deref(Mut)::deref(_mut)` implementations
= note: `#[deny(dangerous_implicit_autorefs)]` on by default
```
https://github.com/eclipse-iceoryx/iceoryx2/actions/runs/15561987907/job/43817405250?pr=801
```
error: implicit autoref creates a reference to the dereference of a raw pointer
--> …
```

[#809] Fix build errors occurring with `nightly` toolchain

---

doc/release-notes/iceoryx2-unreleased.md
iceoryx2-ffi/c/cmake/install.cmake
iceoryx2-ffi/cxx/cmake/fetch-iceoryx-hoofs.cmake
iceoryx2-ffi/cxx/cmake/install.cmake

FFI targets will no longer be included in the installation if iceoryx was obtained through `FetchContent`. Adjusted the CMake warning message to make this obvious.
This PR adjusts the CMake configuration so that the FFI targets can no longer be installed in a build that is configured to use `FetchContent` to obtain `iceoryx`, as the resulting installation would not be usable anyways. …

[#814] gate installation for ffi targets in CMake

---

doc/release-notes/iceoryx2-unreleased.md
iceoryx2-bb/posix/src/file.rs
iceoryx2-bb/posix/src/file_descriptor.rs
iceoryx2-bb/posix/src/group.rs
iceoryx2-bb/posix/src/metadata.rs
iceoryx2-bb/posix/src/ownership.rs
iceoryx2-bb/posix/src/socket_ancillary.rs
iceoryx2-bb/posix/src/user.rs
iceoryx2-bb/posix/tests/group_tests.rs
iceoryx2-bb/posix/tests/ownership_tests.rs
iceoryx2-bb/posix/tests/socket_ancillary_tests.rs
iceoryx2-bb/posix/tests/users_tests.rs

On some platforms the `uid_t` and `gid_t` differ from `u32`. Using a simple `into()` and `try_into()` will lead to clippy warnings.
This PR introduces newtypes for `uid` and `gid`
Closes #822

[#822] Introduce newtypes for 'uid' and 'gid'

---

doc/release-notes/iceoryx2-unreleased.md
iceoryx2-bb/container/src/byte_string.rs

Fix miri for base_string as_bytes API

---

iceoryx2-bb/log/src/logger/console.rs

With #885 not every part of the log message was redirected to stderr but some were still printed to stdout. This PR redirects all parts of the log message to stderr.
No entry in the changelog since this feature was not yet released.
Closes #883

[#883] Redirect all log output to stderr

---

doc/release-notes/iceoryx2-unreleased.md
iceoryx2-bb/elementary-traits/src/zero_copy_send.rs

Removed restriction on `impl Drop` from `ZeroCopySend` trait.
Closes #908

[#908] Remove Drop restriction from ZeroCopySend

---

WORKSPACE.bazel
doc/bazel/README.md
doc/release-notes/iceoryx2-unreleased.md
iceoryx2-ffi/c/CMakeLists.txt
iceoryx2-ffi/cxx/CMakeLists.txt
iceoryx2-ffi/cxx/README.md
internal/scripts/ci_build_and_install_iceoryx_hoofs.ps1
internal/scripts/ci_build_and_install_iceoryx_hoofs.sh
package.xml

This only adds `dl` and `rt` explicitly to target_link_libraries to resolve linking errors in linux with older toolchains.
Closes #855

Fix build and linker error on linux with gcc 8 and 9

---

CMakeLists.txt
iceoryx2-bb/cxx/CMakeLists.txt
iceoryx2-bb/cxx/cmake/iceoryx2-bb-cxxConfig.cmake
iceoryx2-bb/cxx/tests/CMakeLists.txt
iceoryx2-bb/cxx/tests/cmake/googletest.cmake
iceoryx2-bb/cxx/tests/src/main.cpp
iceoryx2-ffi/cxx/CMakeLists.txt

This sets up the CMake build infrastructure for the C++ container library. Other build systems are still missing at the moment.
I also added CTest support for the ffi unit tests with this, as that only required a couple of lines of code, and I changed the method for setting the C++ standard version to use the more robust `target_compile_features`. There is further potential for cleaning up these scripts if we decide to bump the minimum required version in the future:
- 3.23 introduces file sets for `target_sources`
- 3.24 introduces the `COMPILE_WARNING_AS_ERROR` target property
There is some duplication necessary, most visible in the duplicated `googletest.cmake` file. This is due to the fact that iceoryx currently maintains ffi and its tests as a self-contained CMake projects. According …

[#936] CMake build for cxx container library

---

FAQ.md

[#4] Update faq
