Cargo.toml
iceoryx2-bb/posix/Cargo.toml
iceoryx2-bb/posix/src/directory.rs
iceoryx2-bb/posix/src/file.rs
iceoryx2-bb/posix/src/file_descriptor.rs
iceoryx2-bb/posix/src/lib.rs
iceoryx2-bb/posix/tests/access_control_list_tests.rs
iceoryx2-bb/posix/tests/file_descriptor_tests.rs
iceoryx2-pal/posix/Cargo.toml
iceoryx2-pal/posix/build.rs
iceoryx2-pal/posix/src/c/posix.h
iceoryx2-pal/posix/src/c/posix_docs_rs.h
iceoryx2-pal/posix/src/freebsd/acl.rs
iceoryx2-pal/posix/src/freebsd/constants.rs
iceoryx2-pal/posix/src/freebsd/mod.rs
iceoryx2-pal/posix/src/freebsd/types.rs
iceoryx2-pal/posix/src/linux/acl.rs
iceoryx2-pal/posix/src/linux/constants.rs
iceoryx2-pal/posix/src/linux/mod.rs
iceoryx2-pal/posix/src/linux/types.rs
iceoryx2-pal/posix/src/macos/acl.rs
iceoryx2-pal/posix/src/macos/constants.rs
iceoryx2-pal/posix/src/macos/mod.rs
iceoryx2-pal/posix/src/macos/types.rs
iceoryx2-pal/posix/src/windows/acl.rs
iceoryx2-pal/posix/src/windows/constants.rs
iceoryx2-pal/posix/src/windows/mod.rs
iceoryx2-pal/posix/src/windows/types.rs

[#42] Add acl feature flag and deactive it by default

---

doc/release-notes/iceoryx2-unreleased.md
iceoryx2/src/port/event_id.rs
iceoryx2/src/service/messaging_pattern.rs
iceoryx2/src/service/service_name.rs
iceoryx2/src/service/static_config/mod.rs
iceoryx2/tests/service_tests.rs

[#16] same name different messaging pattern allowed

---

doc/release-notes/iceoryx2-unreleased.md
iceoryx2-cal/src/static_storage/file.rs

[#63] Interpret non-existing service directory as no existing services

---

doc/release-notes/iceoryx2-unreleased.md
iceoryx2-pal/posix/src/macos/time.rs

iox2-#80 Fix 'clock_nanosleep' on macOS

---

CODE_OF_CONDUCT.md

[#2] Add code of conduct

---

iceoryx2-bb/posix/src/signal.rs

[#81] Temporary sighandler fix

---

Cargo.toml
doc/how-to-create-an-iceoryx2-release.md
doc/release-notes/iceoryx2-release-template.md
doc/release-notes/iceoryx2-v0.2.1.md
doc/release-notes/iceoryx2-v0.2.2.md

[#77] Set release version to 0.2.2

---

FAQ.md

[#4] Add FAQ entry for resource cleanup

---

doc/release-notes/iceoryx2-unreleased.md
iceoryx2-bb/posix/tests/mutex_tests.rs
iceoryx2/src/service/builder/event.rs
iceoryx2/src/service/builder/publish_subscribe.rs

[#108] Fix open or create race

---

doc/release-notes/iceoryx2-unreleased.md
iceoryx2-bb/container/src/byte_string.rs
iceoryx2-bb/container/tests/byte_string_tests.rs
iceoryx2-bb/lock-free/src/mpmc/container.rs
iceoryx2/src/service/service_name.rs

[#110] Implement `Ord` and `PartialOrd` for `ServiceName`

---

doc/release-notes/iceoryx2-unreleased.md
iceoryx2-bb/lock-free/src/spsc/queue.rs

This PR fixes a broken memory ordering in `spsc::Queue` and does some minor cleanups. …

[#119] Fix memory order issue in 'Queue'

---

.github/PULL_REQUEST_TEMPLATE.md

With the introduction of `#123`, the example in the **References** section will now automatically close that issue. The text is now only available as comment.
1. [x] All checks have …

[#3] Prevent closing of unrelated issues in PR template

---

doc/release-notes/iceoryx2-unreleased.md
iceoryx2-bb/lock-free/src/spmc/unrestricted_atomic.rs

The PR fixes a data race due to operation reordering in `spmc::UnrestrictedAtomic::load` …

[#125] Fix reordering issue in 'spmc::UnrestrictedAtomic::load'

---

CHANGELOG.md
Cargo.toml
benchmarks/README.md
benchmarks/publish-subscribe/Cargo.toml
benchmarks/publish-subscribe/src/main.rs
doc/release-notes/iceoryx2-unreleased.md
iceoryx2/src/sample.rs
iceoryx2/src/sample_mut.rs
iceoryx2/src/service/header/publish_subscribe.rs

[#136] Remove clock_gettime usage; add benchmark configurability

---

benchmarks/publish-subscribe/src/main.rs

[#136] Correct clap usage in benchmark

---

.cirrus.yml
doc/release-notes/iceoryx2-unreleased.md
iceoryx2-cal/tests/event_tests.rs
iceoryx2-pal/posix/src/freebsd/mman.rs
iceoryx2-pal/posix/src/freebsd/mod.rs
iceoryx2-pal/posix/src/freebsd/settings.rs

[#140] fix freebsd

---

doc/release-notes/iceoryx2-unreleased.md
iceoryx2-pal/posix/src/windows/win32_call.rs

[#145] Fix win platform err message for non-utf-8 systems

---

doc/release-notes/iceoryx2-unreleased.md
examples/README.md
examples/examples/docker/README.md
examples/examples/docker/docker-compose.yml

[#83] Add docker example

---

doc/release-notes/iceoryx2-unreleased.md
iceoryx2-bb/testing/src/lib.rs
iceoryx2-bb/testing/src/lifetime_tracker.rs
iceoryx2-cal/src/communication_channel/posix_shared_memory.rs
iceoryx2-cal/src/dynamic_storage/dynamic_storage_configuration.rs
iceoryx2-cal/src/dynamic_storage/mod.rs
iceoryx2-cal/src/dynamic_storage/posix_shared_memory.rs
iceoryx2-cal/src/dynamic_storage/process_local.rs
iceoryx2-cal/src/shared_memory/common.rs
iceoryx2-cal/src/shared_memory/mod.rs
iceoryx2-cal/src/shared_memory_directory/mod.rs
iceoryx2-cal/tests/dynamic_storage_trait_tests.rs
iceoryx2-cal/tests/shared_memory_directory_tests.rs
iceoryx2-cal/tests/shared_memory_trait_tests.rs

[#160] type safe dynamic storage

---

.cirrus.yml
.github/actions/build-and-cache-rust-tool/action.yml
.github/workflows/build-test.yml
iceoryx2-bb/lock-free/tests/bitset_tests.rs
iceoryx2-bb/posix/tests/condition_variable_tests.rs
iceoryx2-bb/posix/tests/mutex_tests.rs
iceoryx2-bb/posix/tests/read_write_mutex_tests.rs
iceoryx2-bb/posix/tests/semaphore_tests.rs
iceoryx2-bb/posix/tests/signal_tests.rs
iceoryx2-bb/testing/src/assert.rs
iceoryx2-bb/testing/src/watchdog.rs
iceoryx2-bb/threadsafe/tests/trigger_queue_tests.rs
iceoryx2-cal/tests/zero_copy_connection_trait_tests.rs
iceoryx2-pal/concurrency-sync/tests/condition_variable_tests.rs
iceoryx2-pal/concurrency-sync/tests/mutex_tests.rs
iceoryx2-pal/configuration/src/lib.rs
iceoryx2-pal/posix/src/macos/mman.rs
iceoryx2-pal/posix/src/macos/semaphore.rs
iceoryx2-pal/posix/src/macos/types.rs
iceoryx2/tests/publisher_tests.rs
iceoryx2/tests/service_event_tests.rs
iceoryx2/tests/service_publish_subscribe_tests.rs
internal/scripts/ci_prepare_archlinux.sh
internal/scripts/ci_prepare_freebsd.sh
internal/scripts/ci_prepare_ubuntu.sh
internal/scripts/ci_prepare_windows.bat

[#3] Add ubuntu stable to github CI

---

doc/how-to-create-an-iceoryx2-release.md

[#5] Update announcement part in release doc

---

.cirrus.yml
.github/workflows/build-test.yml
README.md

[#168] Add ekxide.io as vendor

---

.cirrus.yml
.github/workflows/build-test.yml

[#3] Fix changes CI build

---

examples/examples/complex_data_types/complex_data_types.rs
iceoryx2-bb/posix/tests/condition_variable_tests.rs

[#175] Simplify example

---

doc/release-notes/iceoryx2-unreleased.md
iceoryx2-bb/posix/src/unique_system_id.rs
iceoryx2-bb/posix/tests/unique_system_id_tests.rs

[#181] Fix race in `UniqueSytemId`s

---

.cirrus.yml
.github/actions/build-and-cache-rust-tool/action.yml
.github/actions/download-cached-rust-tool/action.yml
.github/workflows/build-test.yml
iceoryx2-bb/testing/src/assert.rs
iceoryx2-cal/tests/static_storage_trait_tests.rs
iceoryx2/tests/service_tests.rs

This PR adds stress tests for service creation, opening and closing.
The `assert_that` macro is also extended for an `any_of` check.
1. [x] All checks have passed (except …

iox2-#165 stresstests for service creation

---

.github/workflows/build-test.yml
benchmarks/event/src/main.rs
config/iceoryx2.toml
doc/release-notes/iceoryx2-unreleased.md
examples/examples/event/listener.rs
examples/examples/event/notifier.rs
iceoryx2-bb/lock-free/tests/bitset_tests.rs
iceoryx2-bb/testing/src/watchdog.rs
iceoryx2-cal/src/event/common.rs
iceoryx2-cal/src/event/id_tracker/bit_set.rs
iceoryx2-cal/src/event/mod.rs
iceoryx2-cal/src/event/process_local.rs
iceoryx2-cal/src/event/unix_datagram_socket.rs
iceoryx2-cal/tests/event_id_tracker_tests.rs
iceoryx2-cal/tests/event_tests.rs
iceoryx2-cal/tests/reactor_tests.rs
iceoryx2-pal/posix/src/windows/socket.rs
iceoryx2/src/config.rs
iceoryx2/src/lib.rs
iceoryx2/src/port/event_id.rs
iceoryx2/src/port/listener.rs
iceoryx2/src/port/notifier.rs
iceoryx2/src/port/publisher.rs
iceoryx2/src/service/builder/event.rs
iceoryx2/src/service/static_config/event.rs
iceoryx2/tests/service_event_tests.rs
iceoryx2/tests/service_tests.rs

[#173] cleanup event api

---

iceoryx2-bb/container/tests/queue_tests.rs
iceoryx2-bb/container/tests/vec_tests.rs

[#190] add lifetime tests

---

README.md
internal/plots/plot_benchmark_architecture_os_comparision.gp
internal/plots/plot_benchmark_mechanism_comparision.gp

Adjust gnuplot scripts and update benchmark grapsh …

[#4] Adjust gnuplot scripts

---

Cargo.toml
doc/release-notes/iceoryx2-unreleased.md
doc/release-notes/iceoryx2-v0.3.0.md
iceoryx2-bb/container/src/byte_string.rs
iceoryx2-bb/container/src/queue.rs
iceoryx2-cal/tests/static_storage_trait_tests.rs
iceoryx2/tests/service_event_tests.rs

Please verify that the tutorial was followed precisely: https://github.com/eclipse-iceoryx/iceoryx2/blob/main/doc/how-to-create-an-iceoryx2-release.md
1. [x] All checks have passed …

[#77] Prepare v0.3.0 release

---

README.md
internal/plots/benchmark_architecture.svg
internal/plots/benchmark_architecture_os_comparision.dat
internal/plots/benchmark_mechanism.svg
internal/plots/plot_benchmark_architecture_os_comparision.gp
internal/plots/plot_benchmark_mechanism_comparision.gp

It could have been so easy with the SVG backend. …

[#4] Adjust gnuplot script

---

doc/how-to-create-an-iceoryx2-release.md

[#4] Update release doc

---

doc/release-notes/iceoryx2-unreleased.md
iceoryx2/src/port/details/publisher_connections.rs
iceoryx2/src/port/details/subscriber_connections.rs
iceoryx2/src/port/publisher.rs
iceoryx2/src/port/subscriber.rs
iceoryx2/src/service/dynamic_config/publish_subscribe.rs
iceoryx2/src/service/port_factory/subscriber.rs
iceoryx2/tests/service_event_tests.rs
iceoryx2/tests/service_publish_subscribe_tests.rs

[#19] reduce buffer size on subscriber side

---

doc/release-notes/iceoryx2-unreleased.md
iceoryx2-bb/posix/src/clock.rs
iceoryx2-bb/posix/src/config.rs
iceoryx2-bb/posix/src/message_queue.rs
iceoryx2-bb/posix/src/mutex.rs
iceoryx2-bb/posix/src/read_write_mutex.rs
iceoryx2-bb/posix/tests/file_lock_tests.rs
iceoryx2-bb/posix/tests/message_queue_tests.rs
iceoryx2-bb/posix/tests/mutex_tests.rs

[#207] Use performance clock mode

---

FAQ.md
doc/release-notes/iceoryx2-unreleased.md
examples/Cargo.toml
examples/README.md
examples/examples/event/listener.rs
examples/examples/event/notifier.rs
examples/examples/publish_subscribe/publisher.rs
examples/examples/publish_subscribe/subscriber.rs
examples/examples/publish_subscribe_dynamic_data/README.md
examples/examples/publish_subscribe_dynamic_data/publisher.rs
examples/examples/publish_subscribe_dynamic_data/subscriber.rs

[#205] slice api example

---

examples/README.md

[#4] Fix example doc link

---

README.md

iox-#200 update readme

---

FAQ.md
iceoryx2-pal/concurrency-sync/Cargo.toml
iceoryx2-pal/concurrency-sync/src/iox_atomic.rs
iceoryx2/Cargo.toml
iceoryx2/src/lib.rs

[#200] Add 32bit atomic feature flag

---

.cirrus.yml
.github/workflows/build-test.yml
Cargo.toml
doc/release-notes/iceoryx2-unreleased.md
iceoryx2-bb/memory/src/heap_allocator.rs
iceoryx2-bb/posix/src/file_descriptor.rs
iceoryx2-bb/posix/src/permission.rs
iceoryx2-bb/posix/src/thread.rs
iceoryx2-cal/src/serialize/mod.rs
iceoryx2-cal/src/serialize/toml.rs
iceoryx2-pal/posix/build.rs
internal/docker/archlinux-base-devel
internal/docker/ubuntu-22.04
internal/scripts/ci_prepare_archlinux.sh
internal/scripts/ci_prepare_freebsd.sh

[#221] Update all dependencies and set min rust version to 1.75.0

---

doc/release-notes/iceoryx2-unreleased.md
iceoryx2-pal/posix/src/c/posix.h
iceoryx2-pal/posix/src/c/scandir.c
iceoryx2-pal/posix/src/c/sigaction.c
iceoryx2-pal/posix/src/c/socket_macros.c
iceoryx2-pal/posix/src/windows/mman.rs

[#235] Fix windows i686 build

---

doc/release-notes/iceoryx2-unreleased.md
examples/rust/discovery/discovery.rs
iceoryx2-ffi/ffi/src/lib.rs
iceoryx2/src/service/attribute.rs
iceoryx2/src/service/mod.rs
iceoryx2/tests/service_event_tests.rs
iceoryx2/tests/service_publish_subscribe_tests.rs

[#238] Remove xx_with_custom_config

---

.github/workflows/build-test.yml
README.md
benchmarks/event/src/main.rs
benchmarks/publish-subscribe/src/main.rs
config/iceoryx2.toml
doc/release-notes/iceoryx2-unreleased.md
iceoryx2/src/config.rs

[#90] Kebab-case for config files

---

internal/scripts/generate-cov-report.sh

The code for CLI and FFI is currently under development and is not important for the code coverage for now. At least FFI will be re-enabled once finished.
1. [ ] All checks have …

[#213] Ignore cli and ffi code for coverage

---

iceoryx2/src/service/builder/publish_subscribe.rs
iceoryx2/src/service/static_config/message_type_details.rs
iceoryx2/tests/service_publish_subscribe_tests.rs

[#252] manually typed service

---

iceoryx2/src/service/port_factory/event.rs
iceoryx2/src/service/port_factory/mod.rs
iceoryx2/src/service/port_factory/publish_subscribe.rs
iceoryx2/tests/service_tests.rs

[#269] Make node list API consistent

---

examples/c/publish_subscribe/src/publisher.c
iceoryx2-ffi/ffi/src/config.rs
iceoryx2-ffi/ffi/src/lib.rs
iceoryx2-ffi/ffi/src/node.rs
iceoryx2-ffi/ffi/src/node_builder.rs
iceoryx2-ffi/ffi/src/service.rs

This PR adds the required pieces to make `iox2_node_list` …

[#210] Make 'iox2_node_list' functional

---

.cirrus.yml
.clang-format
.github/workflows/build-test.yml
examples/c/publish_subscribe/src/publisher.c
iceoryx2-ffi/c/tests/src/main.cpp
iceoryx2-ffi/cxx/src/dummy.cpp
iceoryx2-ffi/cxx/tests/src/main.cpp
iceoryx2-pal/posix/src/c/dirent.c
iceoryx2-pal/posix/src/c/posix.h
iceoryx2-pal/posix/src/c/scandir.c
iceoryx2-pal/posix/src/c/sigaction.c
iceoryx2-pal/posix/src/c/socket_macros.c

This PR adds a clang-format check to the CI …

[#265] Add clang-format

---

.clang-tidy
CMakeLists.txt
examples/c/publish_subscribe/src/publisher.c
internal/scripts/ci_build_and_test_freebsd.sh
internal/scripts/clang_tidy_scan.sh

This PR adds a preliminary clang-tidy file and a script to scan the files. …

[#265] Add clang-tidy file and script

---

.cirrus.yml
.github/workflows/build-test.yml
iceoryx2-pal/posix/src/c/sigaction.c
internal/docker/ubuntu-22.04
internal/scripts/clang_tidy_scan.sh

This PR enables the clang-tidy check in the CI …

[#265] Add clang-tidy to CI

---

benchmarks/event/src/main.rs
benchmarks/publish-subscribe/src/main.rs

[#281] Configurable log level in benchmark

---

doc/release-notes/iceoryx2-unreleased.md
examples/c/publish_subscribe/src/publisher.c
examples/rust/discovery/discovery.rs
iceoryx2-ffi/ffi/README.md
iceoryx2-ffi/ffi/src/config.rs
iceoryx2-ffi/ffi/src/lib.rs
iceoryx2-ffi/ffi/src/node.rs
iceoryx2-ffi/ffi/src/node_builder.rs
iceoryx2-ffi/ffi/src/node_name.rs
iceoryx2-ffi/ffi/src/service_builder.rs
iceoryx2/src/config.rs
iceoryx2/src/node/mod.rs
iceoryx2/src/service/attribute.rs
iceoryx2/src/service/mod.rs
iceoryx2/tests/node_death_tests.rs
iceoryx2/tests/node_tests.rs
iceoryx2/tests/service_event_tests.rs
iceoryx2/tests/service_publish_subscribe_tests.rs
iceoryx2/tests/service_tests.rs

This PR adjust the naming convention for handles and add preliminary documentation for the naming convention of the iceoryx2-ffi crate.
Additionally, `Config::get_global_config` is renamed to `Config::global_config´.
1. [x] Changelog updated [in the unreleased section][changelog] including API breaking …

[#210] Adjust naming convention for handles

---

doc/release-notes/iceoryx2-unreleased.md
iceoryx2-bb/posix/src/directory.rs

[#287] fix directory mem leak

---

internal/cpp_doc_generator/Doxyfile
internal/cpp_doc_generator/Makefile
internal/cpp_doc_generator/conf.py
internal/cpp_doc_generator/index.rst
internal/cpp_doc_generator/readme.md

[#283] generate cpp documentation

---

doc/release-notes/iceoryx2-unreleased.md
iceoryx2-bb/log/src/log.rs

[#292] Fix log macro bug

---

iceoryx2-ffi/ffi-macros/src/lib.rs
iceoryx2-ffi/ffi/README.md
iceoryx2-ffi/ffi/cbindgen.toml
iceoryx2-ffi/ffi/src/config.rs
iceoryx2-ffi/ffi/src/lib.rs
iceoryx2-ffi/ffi/src/node.rs
iceoryx2-ffi/ffi/src/node_builder.rs
iceoryx2-ffi/ffi/src/node_name.rs

[#210] Simplify pointer handling

---

iceoryx2-ffi/c/CMakeLists.txt
iceoryx2-ffi/cxx/CMakeLists.txt
iceoryx2-ffi/cxx/include/iox2/enum_translation.hpp
iceoryx2-ffi/cxx/include/iox2/node_name.hpp
iceoryx2-ffi/cxx/include/iox2/service_name.hpp
iceoryx2-ffi/cxx/src/node_name.cpp
iceoryx2-ffi/cxx/src/service_name.cpp
iceoryx2-ffi/cxx/tests/src/service_name_tests.cpp
iceoryx2-ffi/ffi/src/api/service_name.rs
iceoryx2/src/service/service_name.rs
internal/cpp_doc_generator/Doxyfile

[#264] cxx service name

---

.cirrus.yml
examples/rust/discovery/discovery.rs
iceoryx2-ffi/ffi/src/api/mod.rs
iceoryx2/src/service/attribute.rs
iceoryx2/src/service/mod.rs
iceoryx2/tests/node_death_tests.rs
iceoryx2/tests/service_publish_subscribe_tests.rs
iceoryx2/tests/service_tests.rs

[#309] Adjust Service::list API

---

CMakeLists.txt
iceoryx2-ffi/cxx/CMakeLists.txt
iceoryx2-ffi/cxx/include/iox2/config.hpp
iceoryx2-ffi/cxx/include/iox2/enum_translation.hpp
iceoryx2-ffi/cxx/include/iox2/internal/callback_context.hpp
iceoryx2-ffi/cxx/include/iox2/node.hpp
iceoryx2-ffi/cxx/include/iox2/node_details.hpp
iceoryx2-ffi/cxx/include/iox2/node_failure_enums.hpp
iceoryx2-ffi/cxx/include/iox2/node_name.hpp
iceoryx2-ffi/cxx/include/iox2/node_state.hpp
iceoryx2-ffi/cxx/include/iox2/service.hpp
iceoryx2-ffi/cxx/include/iox2/service_name.hpp
iceoryx2-ffi/cxx/src/config.cpp
iceoryx2-ffi/cxx/src/node.cpp
iceoryx2-ffi/cxx/src/node_details.cpp
iceoryx2-ffi/cxx/src/node_name.cpp
iceoryx2-ffi/cxx/src/node_state.cpp
iceoryx2-ffi/cxx/src/service_name.cpp
iceoryx2-ffi/cxx/tests/src/node_name_tests.cpp
iceoryx2-ffi/cxx/tests/src/node_state_tests.cpp
iceoryx2-ffi/cxx/tests/src/node_tests.cpp
iceoryx2-ffi/cxx/tests/src/service_name_tests.cpp
iceoryx2-ffi/ffi/src/api/node.rs
iceoryx2-ffi/ffi/src/api/quirks_correction.rs

[#264] cxx node builder

---

iceoryx2-ffi/cxx/CMakeLists.txt
iceoryx2-ffi/cxx/include/iox2/config.hpp
iceoryx2-ffi/cxx/include/iox2/enum_translation.hpp
iceoryx2-ffi/cxx/include/iox2/node.hpp
iceoryx2-ffi/cxx/include/iox2/node_event.hpp
iceoryx2-ffi/cxx/include/iox2/service.hpp
iceoryx2-ffi/cxx/include/iox2/service_error_enums.hpp
iceoryx2-ffi/cxx/include/iox2/service_name.hpp
iceoryx2-ffi/cxx/src/node.cpp
iceoryx2-ffi/cxx/src/service.cpp
iceoryx2-ffi/cxx/tests/src/node_tests.cpp
iceoryx2-ffi/ffi/src/api/node.rs
iceoryx2-ffi/ffi/src/api/quirks_correction.rs
iceoryx2-ffi/ffi/src/api/service.rs
iceoryx2-ffi/ffi/src/tests/node_tests.rs

BASED ON #307 [#264] add service::does_exist

---

iceoryx2-ffi/cxx/include/iox2/enum_translation.hpp
iceoryx2-ffi/cxx/include/iox2/node.hpp
iceoryx2-ffi/cxx/include/iox2/node_event.hpp
iceoryx2-ffi/cxx/src/node.cpp
iceoryx2-ffi/cxx/tests/src/node_tests.cpp
iceoryx2-ffi/ffi/src/api/node.rs
iceoryx2-ffi/ffi/src/api/quirks_correction.rs

BASED ON PR #306 [#264] add node wait

---

iceoryx2-ffi/cxx/tests/src/node_state_tests.cpp
iceoryx2-ffi/cxx/tests/src/node_tests.cpp
iceoryx2-ffi/cxx/tests/src/test.hpp

[#264] typed tests everywhere

---

.clang-tidy
examples/README.md
examples/cxx/event/README.md
examples/cxx/event/src/listener.cpp
examples/cxx/event/src/notifier.cpp
iceoryx2-bb/posix/tests/unix_datagram_socket_tests.rs
iceoryx2-ffi/cxx/CMakeLists.txt
iceoryx2-ffi/cxx/include/iox2/enum_translation.hpp
iceoryx2-ffi/cxx/include/iox2/event_id.hpp
iceoryx2-ffi/cxx/include/iox2/internal/callback_context.hpp
iceoryx2-ffi/cxx/include/iox2/node_name.hpp
iceoryx2-ffi/cxx/include/iox2/port_factory_event.hpp
iceoryx2-ffi/cxx/include/iox2/static_config_event.hpp
iceoryx2-ffi/cxx/src/event_id.cpp
iceoryx2-ffi/cxx/src/listener.cpp
iceoryx2-ffi/cxx/src/node.cpp
iceoryx2-ffi/cxx/src/port_factory_event.cpp
iceoryx2-ffi/cxx/src/static_config_event.cpp
iceoryx2-ffi/cxx/tests/src/service_event_tests.cpp
iceoryx2-ffi/ffi/Cargo.toml
iceoryx2-ffi/ffi/src/api/listener.rs
iceoryx2-ffi/ffi/src/api/mod.rs
iceoryx2-ffi/ffi/src/api/node.rs
iceoryx2-ffi/ffi/src/api/port_factory_event.rs
iceoryx2-ffi/ffi/src/api/quirks_correction.rs
iceoryx2-ffi/ffi/src/api/static_config_event.rs
iceoryx2-ffi/ffi/src/tests/node_tests.rs
iceoryx2/src/port/listener.rs

[#264] listener

---

iceoryx2-ffi/cxx/include/iox2/enum_translation.hpp
iceoryx2-ffi/cxx/include/iox2/port_factory_publisher.hpp
iceoryx2-ffi/cxx/include/iox2/publisher.hpp
iceoryx2-ffi/cxx/include/iox2/unable_to_deliver_strategy.hpp
iceoryx2-ffi/cxx/tests/src/service_publish_subscribe_tests.cpp
iceoryx2-ffi/ffi/src/api/port_factory_publisher_builder.rs
iceoryx2-ffi/ffi/src/api/publisher.rs
iceoryx2/src/port/publisher.rs
iceoryx2/tests/publisher_tests.rs

[#264] blocking publisher cxx api

---

examples/rust/docker/README.md

[#4] Fix docker-compose.yml path in docker example

---

.readthedocs.yaml
internal/cpp_doc_generator/requirements.txt

[#4] Add readthedocs config

---

iceoryx2-ffi/cxx/include/iox2/service_builder_publish_subscribe.hpp
iceoryx2-ffi/cxx/tests/src/service_publish_subscribe_tests.cpp
iceoryx2-ffi/ffi/src/api/service_builder_pub_sub.rs

[#264] safe overflow policy

---

.readthedocs.yaml

[#4] Add further readthedocs apt dependencies

---

doc/release-notes/iceoryx2-unreleased.md
iceoryx2-cal/src/zero_copy_connection/common.rs
iceoryx2-cal/src/zero_copy_connection/mod.rs
iceoryx2-cal/tests/zero_copy_connection_trait_tests.rs
iceoryx2-ffi/cxx/include/iox2/connection_failure.hpp
iceoryx2-ffi/cxx/include/iox2/enum_translation.hpp
iceoryx2-ffi/cxx/include/iox2/subscriber.hpp
iceoryx2-ffi/cxx/include/iox2/subscriber_error.hpp
iceoryx2-ffi/cxx/tests/src/service_publish_subscribe_tests.cpp
iceoryx2-ffi/ffi/src/api/quirks_correction.rs
iceoryx2-ffi/ffi/src/api/subscriber.rs
iceoryx2/src/port/subscriber.rs
iceoryx2/tests/service_publish_subscribe_tests.rs

[#335] subscriber has samples

---

README.md
examples/c/README.md
examples/c/discovery/README.md
examples/c/event/README.md
examples/c/publish_subscribe/README.md
examples/c/publish_subscribe_with_user_header/README.md
examples/cxx/README.md
examples/cxx/discovery/README.md
examples/cxx/event/README.md
examples/cxx/publish_subscribe/README.md
examples/cxx/publish_subscribe_with_user_header/README.md
internal/cpp_doc_generator/Doxyfile
internal/cpp_doc_generator/cxx_event.rst
internal/cpp_doc_generator/cxx_pub_sub.rst
internal/cpp_doc_generator/getting_started.rst
internal/cpp_doc_generator/getting_started_c.rst
internal/cpp_doc_generator/getting_started_cxx.rst
internal/cpp_doc_generator/iceoryx2_c_api.rst
internal/cpp_doc_generator/iceoryx2_cxx_api.rst
internal/cpp_doc_generator/iceoryx_hoofs_api.rst
internal/cpp_doc_generator/index.rst
internal/scripts/ci_prepare_archlinux.sh
internal/scripts/install_dependencies_archlinux.sh
internal/scripts/install_dependencies_ubuntu.sh

[#4] readthedocs intro readme

---

internal/cpp_doc_generator/index.rst

[#4] Fix image link

---

.bazelrc
.github/workflows/build-test.yml
BUILD.bazel
WORKSPACE.bazel
examples/cxx/complex_data_types/BUILD.bazel
examples/cxx/discovery/BUILD.bazel
examples/cxx/event/BUILD.bazel
examples/cxx/publish_subscribe/BUILD.bazel
examples/cxx/publish_subscribe_dynamic_data/BUILD.bazel
examples/cxx/publish_subscribe_with_user_header/BUILD.bazel
examples/cxx/service_attributes/BUILD.bazel
iceoryx2-ffi/c/BUILD.bazel
iceoryx2-ffi/cxx/BUILD.bazel
iceoryx2-ffi/cxx/CMakeLists.txt
iceoryx2-ffi/cxx/tests/BUILD.bazel
iceoryx2-ffi/ffi/BUILD.bazel
internal/scripts/ci_build_and_install_iceoryx_hoofs.ps1
internal/scripts/ci_build_and_install_iceoryx_hoofs.sh

[#329] Fix bazel for external builds

---

.cirrus.yml
.gitignore
BUILD.bazel
MODULE.bazel
MODULE.bazel.lock
WORKSPACE.bazel
iceoryx2-ffi/cxx/CMakeLists.txt
internal/scripts/ci_build_and_install_iceoryx_hoofs.ps1
internal/scripts/ci_build_and_install_iceoryx_hoofs.sh
internal/scripts/ci_build_and_test_freebsd.sh

[#329] Export license file for bazel and another external build fix

---

BUILD.bazel

[#329] Fix export license for bazel

---

iceoryx2-bb/system-types/src/file_name.rs
iceoryx2-bb/trait-tests/tests/semantic_string_tests.rs
iceoryx2-cal/tests/shm_allocator_trait_tests.rs
iceoryx2-ffi/cxx/include/iox2/port_factory_event.hpp
iceoryx2-ffi/cxx/include/iox2/port_factory_publish_subscribe.hpp
iceoryx2-ffi/cxx/include/iox2/service_id.hpp
iceoryx2-ffi/cxx/src/port_factory_event.cpp
iceoryx2-ffi/ffi/src/api/iceoryx2_settings.rs
iceoryx2-ffi/ffi/src/api/service_builder.rs
iceoryx2-ffi/ffi/src/api/static_config.rs
iceoryx2-ffi/ffi/src/api/subscriber.rs
iceoryx2-ffi/ffi/src/tests/iceoryx2_settings_tests.rs
iceoryx2-ffi/ffi/src/tests/mod.rs
iceoryx2/src/node/mod.rs
iceoryx2/src/service/builder/mod.rs
iceoryx2/src/service/mod.rs
iceoryx2/src/service/naming_scheme.rs
iceoryx2/src/service/port_factory/event.rs
iceoryx2/src/service/port_factory/mod.rs
iceoryx2/src/service/port_factory/publish_subscribe.rs
iceoryx2/src/service/service_id.rs
iceoryx2/src/service/static_config/mod.rs
iceoryx2/tests/service_tests.rs

[#294] Introduce ServiceId

---

benchmarks/README.md
benchmarks/event/src/main.rs
benchmarks/publish-subscribe/src/main.rs
doc/release-notes/iceoryx2-unreleased.md
internal/plots/benchmark_architecture_os_comparision.dat

[#360] benchmark improvements

---

config/README.md
config/iceoryx2.toml
doc/release-notes/iceoryx2-unreleased.md
iceoryx2-bb/container/src/queue.rs
iceoryx2-bb/container/tests/queue_tests.rs
iceoryx2-cal/src/static_storage/file.rs
iceoryx2-cal/src/static_storage/process_local.rs
iceoryx2-ffi/ffi/src/api/subscriber.rs
iceoryx2/src/config.rs
iceoryx2/src/port/details/publisher_connections.rs
iceoryx2/src/port/subscriber.rs
iceoryx2/src/sample.rs
iceoryx2/tests/sample_tests.rs
iceoryx2/tests/service_publish_subscribe_tests.rs

[#337] samples rejected after publisher disconnected

---

internal/plots/benchmark_architecture_os_comparision.dat

[#4] Update benchmark numbers

---

iceoryx2-bb/posix/tests/unix_datagram_socket_tests.rs
iceoryx2-pal/posix/src/macos/inet.rs
iceoryx2/src/node/mod.rs

[#3] Fix clippy warning

---

iceoryx2-ffi/ffi/src/api/service_builder_pub_sub.rs
iceoryx2/src/service/builder/publish_subscribe.rs
iceoryx2/tests/publisher_tests.rs
iceoryx2/tests/service_publish_subscribe_tests.rs

[#377] Use reference as argument

---

examples/README.md
examples/cxx/CMakeLists.txt
examples/cxx/domains/BUILD.bazel
examples/cxx/domains/CMakeLists.txt
examples/cxx/domains/README.md
examples/cxx/domains/src/discovery.cpp
examples/cxx/domains/src/publisher.cpp
examples/cxx/domains/src/subscriber.cpp
examples/cxx/domains/src/transmission_data.hpp
examples/rust/domains/publisher.rs
iceoryx2-ffi/cxx/include/iox2/config.hpp
iceoryx2-ffi/cxx/src/config.cpp
iceoryx2-ffi/cxx/src/node.cpp
iceoryx2-ffi/ffi/src/api/config.rs
iceoryx2-ffi/ffi/src/api/node_builder.rs

[#370] domain separation cpp example

---

iceoryx2-ffi/cxx/include/iox2/service_builder_publish_subscribe.hpp
iceoryx2-ffi/cxx/tests/src/service_publish_subscribe_tests.cpp
iceoryx2-ffi/ffi/src/api/service_builder_pub_sub.rs

This PR extends the available parameter for the pub-sub service builder. …

[#264] Extend service builder pub sub parameter

---

doc/release-notes/iceoryx2-unreleased.md
package.xml

As per title
1. [ ] ~~Every source code file has a copyright header with `SPDX-License-Identifier: Apache-2.0 OR MIT`~~
1. [ ] ~~Tests follow the [best practice for testing][testing]~~
[eca]: …

[#381] Add colcon package for iceoryx2

---

iceoryx2-ffi/cxx/include/iox2/publisher.hpp
iceoryx2-ffi/cxx/include/iox2/subscriber.hpp
iceoryx2-ffi/cxx/tests/src/service_publish_subscribe_tests.cpp
iceoryx2-ffi/ffi/src/api/publisher.rs
iceoryx2-ffi/ffi/src/api/subscriber.rs
iceoryx2/src/port/publisher.rs

[#264] update connections

---

iceoryx2/src/service/mod.rs
iceoryx2/src/service/service_id.rs
iceoryx2/src/service/static_config/mod.rs

[#388] Remove create_uuid and use ServiceId instead

---

.cirrus.yml
CMakeLists.txt
Cargo.toml
doc/release-notes/iceoryx2-v0.4.1.md
examples/c/discovery/CMakeLists.txt
examples/c/domains/CMakeLists.txt
examples/c/event/CMakeLists.txt
examples/c/publish_subscribe/CMakeLists.txt
examples/c/publish_subscribe_with_user_header/CMakeLists.txt
examples/cxx/complex_data_types/CMakeLists.txt
examples/cxx/discovery/CMakeLists.txt
examples/cxx/domains/CMakeLists.txt
examples/cxx/event/CMakeLists.txt
examples/cxx/publish_subscribe/CMakeLists.txt
examples/cxx/publish_subscribe_dynamic_data/CMakeLists.txt
examples/cxx/publish_subscribe_with_user_header/CMakeLists.txt
examples/cxx/service_attributes/CMakeLists.txt
iceoryx2-cli/iox2/src/commands.rs
iceoryx2-ffi/c/BUILD.bazel
iceoryx2-ffi/c/cmake/iceoryx2-cConfigVersion.cmake
iceoryx2-ffi/cxx/cmake/iceoryx2-cxxConfigVersion.cmake
package.xml

[#77] 0.4.1 release

---

iceoryx2-bb/posix/tests/thread_tests.rs

[#422] Use assert_that(..., time_at_least ...)

---

iceoryx2/src/service/builder/publish_subscribe.rs
iceoryx2/tests/service_publish_subscribe_tests.rs

* Public API `open_or_create_with_attributes` should be tested.
* update the doc of open_or_create_with_attributes.
1. [X] Add sensible notes for the reviewer
1. [X] PR title is short, expressive and meaningful
1. [X] Relevant issues are linked in the [References](#references) section
1. [X] Every source code file has a copyright header with `SPDX-License-Identifier: Apache-2.0 OR MIT`
1. [X] Branch follows the naming format (`iox2-123-introduce-posix-ipc-example`)
1. [X] Commits messages are according to this [guideline][commit-guidelines]
1. [X] Tests follow the [best practice for testing][testing]
1. [X] Changelog updated [in the unreleased section][changelog] including API breaking changes
1. [X] All checks have passed (except `task-list-completed`) …

[#213] test public API open_or_create_with_attributes

---

FAQ.md
examples/README.md

[#436] Add repr(C) restriction

---

README.md
iceoryx2-cal/Cargo.toml
iceoryx2-cal/src/communication_channel/message_queue.rs
iceoryx2-cal/src/dynamic_storage/posix_shared_memory.rs
iceoryx2/Cargo.toml
iceoryx2/src/lib.rs

[#460] Add dev_permissions feature flag

---

FAQ.md
doc/how-to-create-an-iceoryx2-release.md
examples/c/event_multiplexing/README.md
examples/c/event_multiplexing/src/wait.c
examples/cxx/event_multiplexing/README.md
examples/cxx/event_multiplexing/src/wait.cpp
examples/rust/event_multiplexing/README.md
examples/rust/event_multiplexing/wait.rs
internal/cpp_doc_generator/cxx_event.rst
internal/cpp_doc_generator/cxx_pub_sub.rst

[#4] add waitset hints

---

.github/workflows/build-test.yml

This PR fixes the CI setup after the deactivation of MinGW in #466. …

[#3] Fix CI after MinGW deactivation

---

iceoryx2-ffi/cxx/tests/src/service_event_tests.cpp
iceoryx2-ffi/cxx/tests/src/service_publish_subscribe_tests.cpp
iceoryx2/tests/service_event_tests.rs
iceoryx2/tests/service_publish_subscribe_tests.rs

This PR adds tests that proof that a service exists as long as a single port is still available. The when a single port is still living the service can be opened, no longer be created, since it still exists etc. …

[#493] add tests

---

iceoryx2-ffi/cxx/include/iox2/sample_mut.hpp

1. Proper pointer const-ness when returning `ImmutableSlice` in non-mut `payload()` method
1. [ ] Changelog updated [in the unreleased section][changelog] including API breaking changes
1. [ ] Assign PR to reviewer …

[#490] bugfix in cxx slice api

---

iceoryx2-ffi/cxx/include/iox2/file_descriptor.hpp

All methods of `FileDescriptorView` are private but `file_descriptor` and `unsafe_native_handle` needs to be public.
1. [ x Tests follow the [best practice for testing][testing] …

[#264] Fix accessability of 'FileDescriptorView' methods

---

iceoryx2-ffi/cxx/include/iox2/waitset.hpp
iceoryx2-ffi/cxx/src/waitset.cpp
iceoryx2-ffi/cxx/tests/src/waitset_tests.cpp
iceoryx2-ffi/ffi/src/api/waitset.rs
iceoryx2/src/port/waitset.rs
iceoryx2/tests/waitset_tests.rs

From @elBoberido :
Unforunately this is already merged else I would have objected
- why is this necessary when there is already the deadline option?
- why use a surrogate for cases when no timeout is required?
- this makes the API more cumbersome for all the users who do not need/want a timeout since it's not obvious what to use
- either use an `Option<Duration>` or add an additional `*_with_timeout` function
Answers:
> - why is this necessary when there is already the deadline option?
Do you mean interval? Deadline is an attached listener where a notification is expected before the deadline has passed. An interval is a recurring event, and an explicit timeout option makes it possible for the user to add a simple max wait time option.
> - why use a surrogate for cases when no timeout is …

[#533] add timeout to waitset

---

BUILD.bazel
Cargo.Bazel.lock
Cargo.lock
Cargo.toml
WORKSPACE.bazel
benchmarks/README.md
benchmarks/event/src/main.rs
benchmarks/publish-subscribe/src/main.rs
benchmarks/queue/BUILD.bazel
benchmarks/queue/Cargo.toml
benchmarks/queue/src/main.rs
doc/release-notes/iceoryx2-unreleased.md

[#535] queue benchmark

---

doc/release-notes/iceoryx2-unreleased.md

[#532] Update release notes

---

README.md

[#4] Update contributor list

---

.cirrus.yml
doc/release-notes/iceoryx2-v0.5.0.md

The introduced mechanism to skip builds on the Cirrus CI for draft PRs, broke the main CI build.
Relates to #3

[#3] Deaktivate draft handling on Cirrus CI

---

internal/scripts/crates_io_publish_script.sh

[#3] Do not publish ffi

---

iceoryx2-ffi/ffi/src/api/message_type_details.rs
iceoryx2-ffi/ffi/src/api/static_config.rs

[#3] Fix rust 1.84 clippy warnings

---

iceoryx2/src/port/details/data_segment.rs
iceoryx2/src/service/dynamic_config/event.rs
iceoryx2/src/service/dynamic_config/publish_subscribe.rs

[#585] Extend introspection interface

---

ROADMAP.md
doc/how-to-create-an-iceoryx2-release.md

[#4] Update roadmap

---

doc/release-notes/iceoryx2-unreleased.md
iceoryx2-ffi/cxx/include/iox2/attribute_set.hpp
iceoryx2-ffi/cxx/src/attribute_set.cpp
iceoryx2/src/service/attribute.rs
iceoryx2/tests/attribute_tests.rs

[#590] easier access to attributes

---

doc/release-notes/iceoryx2-unreleased.md
iceoryx2-bb/posix/BUILD.bazel
iceoryx2-bb/posix/src/lib.rs
iceoryx2-bb/posix/src/socket_pair.rs
iceoryx2-bb/posix/tests/socket_pair_tests.rs
iceoryx2-pal/posix/src/freebsd/socket.rs
iceoryx2-pal/posix/src/linux/socket.rs
iceoryx2-pal/posix/src/macos/socket.rs
iceoryx2-pal/posix/src/windows/socket.rs
iceoryx2-pal/posix/src/windows/win32_handle_translator.rs
iceoryx2-pal/posix/tests/win32_select_tests.rs

Currently, the process local service variant uses unix datagram sockets as basis for events. This is not at all restricted to the same process since they have a file system representation. We had to make this switch from semaphores with the introduction of the waitset that required listeners based on file descriptors.
`socketpairs` allow the user to create two local, connected sockets. This shall become the new foundation for process local events.
On Windows the socket pair is created via two unix stream sockets that are connected and then the file system representation is deleted. Furthermore, to ensure there are no clashes in the file system representation, the socket path has a suffix consisting of the pid and a counter. …

[#508] introduce socketpairs

---

doc/release-notes/iceoryx2-unreleased.md
iceoryx2-cal/src/zero_copy_connection/common.rs
iceoryx2-cal/src/zero_copy_connection/mod.rs
iceoryx2-cal/tests/zero_copy_connection_trait_tests.rs
iceoryx2/src/port/publisher.rs

[#596] zero copy connection cleanup

---

doc/release-notes/iceoryx2-unreleased.md
iceoryx2/src/service/local.rs

[#508] Use socketpairs for process local events

---

config/README.md
doc/release-notes/iceoryx2-unreleased.md
iceoryx2-bb/posix/src/system_configuration.rs
iceoryx2-bb/posix/src/user.rs
iceoryx2-bb/posix/tests/users_tests.rs
iceoryx2-ffi/cxx/include/iox2/config_creation_error.hpp
iceoryx2-ffi/cxx/include/iox2/enum_translation.hpp
iceoryx2-ffi/cxx/tests/src/enum_conversion_tests.cpp
iceoryx2-ffi/ffi/src/api/config.rs
iceoryx2-pal/posix/src/freebsd/constants.rs
iceoryx2-pal/posix/src/libc/constants.rs
iceoryx2-pal/posix/src/linux/constants.rs
iceoryx2-pal/posix/src/macos/constants.rs
iceoryx2-pal/posix/src/windows/constants.rs
iceoryx2/src/config.rs
iceoryx2/tests/config_tests.rs
iceoryx2/tests/node_tests.rs

Adds the default config lookup paths (according to XDG - at least on UNIX platforms) to the platform abstraction.
Via the posix wrappers they become available to the user. The user object provides now a `config_dir` method to obtain the users default config dir ($HOME/.config) and the system_configuration provides the global config path `/etc` on POSIX and `C:\` on Windows.
Relates to …

[#442] add config paths to platform

---

README.md
iceoryx2-bb/elementary/src/placement_default.rs

This PR implements `PlacementDefault` for `UnsafeCell`.
Closes #625

Iox2 625 placementdefault for unsafecell

---

doc/bazel/README.md

This PR updates the bazel documentation for external builds
Closes #

[#4] Fix bazel documentation

---

Cargo.Bazel.lock
WORKSPACE.bazel
doc/bazel/README.md
iceoryx2-ffi/cxx/CMakeLists.txt
iceoryx2-ffi/cxx/tests/src/service_event_tests.cpp
iceoryx2-ffi/cxx/tests/src/test.hpp
iceoryx2-ffi/cxx/tests/src/waitset_tests.cpp
internal/scripts/ci_build_and_install_iceoryx_hoofs.ps1
internal/scripts/ci_build_and_install_iceoryx_hoofs.sh
internal/scripts/ci_build_and_test_freebsd.sh
package.xml

[#3] freebsd llvm uses newest version

---

Cargo.Bazel.lock
Cargo.lock
Cargo.toml
doc/release-notes/iceoryx2-unreleased.md
iceoryx2-bb/lock-free/BUILD.bazel
iceoryx2-bb/lock-free/Cargo.toml
iceoryx2-bb/lock-free/src/mpmc/unique_index_set.rs
iceoryx2-bb/posix/BUILD.bazel
iceoryx2-bb/posix/Cargo.toml
iceoryx2-bb/posix/src/permission.rs
iceoryx2-bb/posix/src/signal.rs
iceoryx2-cal/BUILD.bazel
iceoryx2-cal/Cargo.toml

This PR replaces `bitflags` with a custom implementation, removes the unused `ouroboros` and removes one usage of `tiny-fn`.
Closes #640

[#640] Reduce dependencies

---

iceoryx2-ffi/cxx/include/iox2/service_builder_publish_subscribe.hpp
iceoryx2-ffi/cxx/tests/src/service_publish_subscribe_tests.cpp

This PR adds the possibility to set the user header type name in the C++ binding.
Relates to #643

[#643] Make user header type name customizable for C++ binding

---

README.md
doc/user-documentation/bb-to-std-mapping.md

This commit provides an overview of the building blocks and their similarities to the Rust std types
Closes #648

[#648] Add bb to std mapping doc

---

iceoryx2-bb/posix/src/system_configuration.rs
iceoryx2-pal/configuration/src/lib.rs
iceoryx2-pal/posix/src/freebsd/constants.rs
iceoryx2-pal/posix/src/libc/constants.rs
iceoryx2-pal/posix/src/linux/constants.rs
iceoryx2-pal/posix/src/macos/constants.rs
iceoryx2-pal/posix/src/windows/constants.rs

[#657] Move config paths into platform configuration

---

Cargo.lock
iceoryx2-ffi/cxx/include/iox2/internal/service_builder_publish_subscribe_internal.hpp
iceoryx2-ffi/cxx/include/iox2/service_builder_publish_subscribe.hpp
iceoryx2-ffi/cxx/tests/src/service_publish_subscribe_tests.cpp
iceoryx2-ffi/ffi/src/api/service_builder.rs

This PR adds the automatic conversion from fixed-size integer payload types to the Rust pendants: If a payload type name is specified (also for inner types of slices), this will be used. (Slices of) fixed-size integers will be converted to the payload type name of the Rust pendants. Otherwise, `typeid` is used as payload type name.
[changelog]: …

[#643] Automatically convert payload type name for fixed size integers and slices

---

.github/workflows/build-test.yml
.github/workflows/miri-check.yml

Will fix CVE-2025-30066
https://nvd.nist.gov/vuln/detail/CVE-2025-30066
This PR will pin all versions of the actions. 
Dependabot is also capable of pinning to future tag releases
and will maintain the comment that describes the shasum.
https://github.com/dependabot/dependabot-core/issues/4691
Used https://github.com/sethvargo/ratchet to generate the shas.
Closes #650

[#650] Pin GH actions

---

.github/workflows/build-test.yml
.github/workflows/miri-check.yml

#652 deactivated the miri CI job. The actions are now pinned an the miri CI job can be re-enabled.
Relates to #3

[#3] Re-enable miri workflow

---

doc/release-notes/iceoryx2-unreleased.md
iceoryx2-cli/BUILD.bazel
iceoryx2-cli/iox2-config/src/main.rs
iceoryx2-cli/iox2-node/src/main.rs
iceoryx2-cli/iox2-service/src/main.rs
iceoryx2-cli/iox2/src/main.rs

1. Reduce indentation
2. Ensure `LogLevel` is set consistently
3. Adds `iox2-config` to bazel build
Closes #646

[#646] code cleanliness in cli binaries

---

doc/release-notes/iceoryx2-unreleased.md
iceoryx2-ffi/cxx/include/iox2/attribute_set.hpp
iceoryx2-ffi/cxx/include/iox2/service_id.hpp
iceoryx2-ffi/cxx/src/attribute_set.cpp
iceoryx2-ffi/cxx/src/service_id.cpp
iceoryx2-ffi/cxx/tests/src/attribute_tests.cpp
iceoryx2-ffi/cxx/tests/src/service_event_tests.cpp
iceoryx2-ffi/cxx/tests/src/service_publish_subscribe_tests.cpp
iceoryx2-ffi/cxx/tests/src/service_tests.cpp
iceoryx2-ffi/ffi/src/api/attribute_set.rs
iceoryx2-ffi/ffi/src/tests/iceoryx2_settings_tests.rs
iceoryx2/src/service/attribute.rs
iceoryx2/src/service/service_id.rs
iceoryx2/tests/attribute_tests.rs
iceoryx2/tests/service_request_response_builder_tests.rs

[#697] improve naming

---

doc/release-notes/iceoryx2-unreleased.md
iceoryx2/src/waitset.rs
iceoryx2/tests/waitset_tests.rs

When the waitset has nothing attached which can generates wakeups, e.g. just a `notification` and not an `interval` or `deadline`, the `wait_and_process_once_with_timeout` blocks indefinitely instead of returning after the timeout is reached.
This PR fixes the logic to determine when the waitset needs to wait on a timeout.
Closes #695

[#695] Fix 'wait_and_process_once_with_timeout` deadlock

---

BUILD.bazel
Cargo.lock
Cargo.toml
WORKSPACE.bazel
benchmarks/README.md
benchmarks/request-response/BUILD.bazel
benchmarks/request-response/Cargo.toml
benchmarks/request-response/src/main.rs
doc/release-notes/iceoryx2-unreleased.md

[#687] add benchmark

---

doc/development-setup/windows.md

This PR adds the documentation on how to setup the development environment for iceoryx2 on Windows.
Relates to #4

[4] Add documentation for Windows development setup

---

doc/release-notes/iceoryx2-unreleased.md
iceoryx2/src/active_request.rs
iceoryx2/src/port/client.rs
iceoryx2/src/port/details/data_segment.rs
iceoryx2/src/port/mod.rs
iceoryx2/src/port/server.rs
iceoryx2/src/request_mut.rs
iceoryx2/src/response.rs
iceoryx2/src/response_mut.rs
iceoryx2/src/response_mut_uninit.rs
iceoryx2/src/service/dynamic_config/event.rs
iceoryx2/src/service/dynamic_config/publish_subscribe.rs
iceoryx2/src/service/dynamic_config/request_response.rs
iceoryx2/src/service/header/request_response.rs
iceoryx2/tests/active_request_tests.rs
iceoryx2/tests/pending_response_tests.rs
iceoryx2/tests/service_event_tests.rs
iceoryx2/tests/service_publish_subscribe_tests.rs
iceoryx2/tests/service_request_response_tests.rs

[#685] access port details of service

---

iceoryx2/tests/service_tests.rs

[#728] Add service tests

---

Cargo.lock
Cargo.toml

Bumps the version of `human_panic` to fix this deprecation warning:
```
warning: `iceoryx2-cli` (bin "iox2-service" test) generated 2 warnings
warning: use of deprecated type alias `std::panic::PanicInfo`: use `PanicHookInfo` instead
--> iceoryx2-cli/iox2/src/main.rs:31:9
|
31 |         setup_panic!();
|         ^^^^^^^^^^^^^^
|
= note: `#[warn(deprecated)]` on by default
= note: this warning originates in the macro `$crate::setup_panic` which comes from the expansion of the macro `setup_panic` (in Nightly builds, run with -Z macro-backtrace for more info)
```
Seen in `--release` builds, e.g. https://github.com/eclipse-iceoryx/iceoryx2/runs/42103342565 …

[#646] Fix warning about use of deprecated `std::panic::PanicInfo` in CLIs

---

config/README.md
config/iceoryx2.toml
doc/release-notes/iceoryx2-unreleased.md
iceoryx2-ffi/cxx/include/iox2/config.hpp
iceoryx2-ffi/cxx/src/config.cpp
iceoryx2-ffi/cxx/tests/src/config_tests.cpp
iceoryx2-ffi/ffi/src/api/config.rs
iceoryx2/src/config.rs
iceoryx2/src/port/client.rs
iceoryx2/src/port/publisher.rs
iceoryx2/src/service/config_scheme.rs
iceoryx2/src/service/dynamic_config/request_response.rs
iceoryx2/src/service/mod.rs
iceoryx2/src/service/naming_scheme.rs
iceoryx2/src/service/stale_resource_cleanup.rs
iceoryx2/tests/node_death_tests.rs

[#688] request response resource cleanup

---

iceoryx2-ffi/cxx/CMakeLists.txt
iceoryx2-ffi/cxx/include/iox2/client_details.hpp
iceoryx2-ffi/cxx/include/iox2/dynamic_config_event.hpp
iceoryx2-ffi/cxx/include/iox2/dynamic_config_publish_subscribe.hpp
iceoryx2-ffi/cxx/include/iox2/dynamic_config_request_response.hpp
iceoryx2-ffi/cxx/include/iox2/internal/callback_context.hpp
iceoryx2-ffi/cxx/include/iox2/listener_details.hpp
iceoryx2-ffi/cxx/include/iox2/node_id.hpp
iceoryx2-ffi/cxx/include/iox2/notifier_details.hpp
iceoryx2-ffi/cxx/include/iox2/publisher_details.hpp
iceoryx2-ffi/cxx/include/iox2/server_details.hpp
iceoryx2-ffi/cxx/include/iox2/subscriber_details.hpp
iceoryx2-ffi/cxx/include/iox2/unique_port_id.hpp
iceoryx2-ffi/cxx/src/client_details.cpp
iceoryx2-ffi/cxx/src/dynamic_config_event.cpp
iceoryx2-ffi/cxx/src/dynamic_config_publish_subscribe.cpp
iceoryx2-ffi/cxx/src/dynamic_config_request_response.cpp
iceoryx2-ffi/cxx/src/listener_details.cpp
iceoryx2-ffi/cxx/src/notifier_details.cpp
iceoryx2-ffi/cxx/src/publisher_details.cpp
iceoryx2-ffi/cxx/src/server_details.cpp
iceoryx2-ffi/cxx/src/subscriber_details.cpp
iceoryx2-ffi/cxx/tests/src/service_event_tests.cpp
iceoryx2-ffi/cxx/tests/src/service_publish_subscribe_tests.cpp
iceoryx2-ffi/cxx/tests/src/service_request_response_tests.cpp
iceoryx2-ffi/ffi/src/api/port_factory_event.rs
iceoryx2-ffi/ffi/src/api/port_factory_pub_sub.rs
iceoryx2-ffi/ffi/src/api/port_factory_request_response.rs

[#685] cxx binding

---

Cargo.lock
examples/Cargo.toml
examples/rust/discovery_service/discovery_service.rs
iceoryx2-services/discovery/BUILD.bazel
iceoryx2-services/discovery/Cargo.toml
iceoryx2-services/discovery/src/service_discovery/service.rs
iceoryx2-services/discovery/tests/service_discovery_service_tests.rs

Updates the service discovery service to use the loan API.
To verify functionality, run these commands in three terminals:
```
cargo build -p iceoryx2-cli
cargo run --bin iox2 -- service-debug discovery
```
```
cargo run --example discovery_service
```
```
cargo run --example publish_subscribe_subscriber
```
Closes #708

[#708] Use loan API in service discovery service

---

iceoryx2-bb/container/src/semantic_string.rs
iceoryx2-bb/derive-macros/src/lib.rs
iceoryx2-bb/derive-macros/src/zero_copy_send_compile_tests.rs
iceoryx2-bb/derive-macros/tests/zero_copy_send_tests.rs
iceoryx2-bb/posix/src/clock.rs
iceoryx2-cal/src/zero_copy_connection/mod.rs
iceoryx2/src/service/static_config/message_type_details.rs
iceoryx2/tests/service_publish_subscribe_tests.rs

[#741] Check if type is annotated with `#[repr(C)]` in ZeroCopySend macro

---

CONTRIBUTING.md
README.md

We are not deleting the thank you mentions of the contributors but using the GitHub mechanism itself which lists all contributors directly on the main page and also lists them here: https://github.com/eclipse-iceoryx/iceoryx2/graphs/contributors
With this approach no one is overlooked.
Relates to #4

[#4] Remove explicit contributor mentions

---

README.md

Re-add `Thanks To All Contributor` to have a direct link from crates.io to the contributors.
Relates to #4

[#4] Add generic thank you to the README

---

config/README.md
config/iceoryx2.toml
iceoryx2-ffi/cxx/include/iox2/config.hpp
iceoryx2-ffi/cxx/src/config.cpp
iceoryx2-ffi/ffi/src/api/config.rs
iceoryx2/src/active_request.rs
iceoryx2/src/config.rs
iceoryx2/src/port/server.rs
iceoryx2/src/response_mut.rs
iceoryx2/tests/active_request_tests.rs
iceoryx2/tests/server_tests.rs
iceoryx2/tests/service_request_response_tests.rs

[#748] introduce expired connection buffer on server side

---

.cirrus.yml
CHANGELOG.md

This PR reduces the Cirrus CI jobs on the main branch to the same jobs that run with the PRs.
Additionally, the CHANGELOG.md file was not updated for a long time.
Relates to #3 
Relates to #4

[#3; #4] Reduce Cirrus CI Jobs and Update CHANGELOG.md

---

internal/scripts/crates_io_publish_script.sh

[#77] Fix crates io publish script

---

doc/how-to-create-an-iceoryx2-release.md
doc/release-notes/iceoryx2-unreleased.md
iceoryx2-bb/container/src/byte_string.rs
iceoryx2-bb/container/src/semantic_string.rs
iceoryx2-bb/derive-macros/src/lib.rs
iceoryx2-bb/posix/src/clock.rs
iceoryx2-bb/posix/src/unique_system_id.rs
iceoryx2-bb/system-types/src/base64url.rs
iceoryx2-bb/system-types/src/file_name.rs
iceoryx2-bb/system-types/src/file_path.rs
iceoryx2-bb/system-types/src/group_name.rs
iceoryx2-bb/system-types/src/path.rs
iceoryx2-bb/system-types/src/user_name.rs
iceoryx2-cal/src/zero_copy_connection/mod.rs
iceoryx2/src/port/port_identifiers.rs
iceoryx2/src/service/attribute.rs
iceoryx2/src/service/header/publish_subscribe.rs
iceoryx2/src/service/header/request_response.rs
iceoryx2/src/service/service_id.rs
iceoryx2/src/service/service_name.rs
iceoryx2/src/service/static_config/event.rs
iceoryx2/src/service/static_config/messaging_pattern.rs
iceoryx2/src/service/static_config/mod.rs
iceoryx2/src/service/static_config/publish_subscribe.rs
iceoryx2/src/service/static_config/request_response.rs
iceoryx2/tests/service_static_config_tests.rs

[#759] fix public dependency

---

.cirrus.yml
README.md

The fee compute credits on Cirrus CI are too limited for a high pace open source project like iceoryx2. Therefore Cirrus CI will be fully deactivated.
Closes #

[#3] Fully deactivate Cirrus CI

---

doc/release-notes/iceoryx2-unreleased.md
examples/c/event_multiplexing/src/wait.c

[#766] Fix event multiplexing C example

---

doc/release-notes/iceoryx2-unreleased.md
iceoryx2-bb/posix/src/group.rs
iceoryx2-bb/posix/src/user.rs
iceoryx2-bb/posix/tests/file_descriptor_tests.rs
iceoryx2-bb/posix/tests/group_tests.rs
iceoryx2-bb/posix/tests/users_tests.rs
iceoryx2-cli/iox2-config/src/commands.rs
iceoryx2/src/config.rs

[#780] make user group details optional

---

doc/release-notes/iceoryx2-unreleased.md
iceoryx2-cli/iox2-config/src/cli.rs

This PR prints the available options for `iox2 config show`
* [~] Tests follow the [best practice for testing][testing]
Closes #788

[#788] Make 'iox2 config show' print the available options

---

doc/release-notes/iceoryx2-unreleased.md
iceoryx2-pal/posix/src/macos/pthread.rs

[#799] fix race in pthread create

---

doc/release-notes/iceoryx2-unreleased.md
iceoryx2-cal/src/communication_channel/mod.rs
iceoryx2-cal/src/communication_channel/recommended.rs
iceoryx2-cal/src/dynamic_storage/mod.rs
iceoryx2-cal/src/dynamic_storage/recommended.rs
iceoryx2-cal/src/event/mod.rs
iceoryx2-cal/src/event/recommended.rs
iceoryx2-cal/src/hash/mod.rs
iceoryx2-cal/src/hash/recommended.rs
iceoryx2-cal/src/monitoring/mod.rs
iceoryx2-cal/src/monitoring/recommended.rs
iceoryx2-cal/src/reactor/mod.rs
iceoryx2-cal/src/reactor/recommended.rs
iceoryx2-cal/src/resizable_shared_memory/mod.rs
iceoryx2-cal/src/resizable_shared_memory/recommended.rs
iceoryx2-cal/src/serialize/mod.rs
iceoryx2-cal/src/serialize/recommended.rs
iceoryx2-cal/src/shared_memory/mod.rs
iceoryx2-cal/src/shared_memory/recommended.rs
iceoryx2-cal/src/static_storage/mod.rs
iceoryx2-cal/src/static_storage/recommended.rs
iceoryx2-cal/src/zero_copy_connection/mod.rs
iceoryx2-cal/src/zero_copy_connection/recommended.rs
iceoryx2/src/service/ipc.rs
iceoryx2/src/service/local.rs

[#806] target optimal concept recommendation

---

iceoryx2-bb/container/src/flatmap.rs
iceoryx2-bb/container/src/lib.rs
iceoryx2-bb/container/src/queue.rs
iceoryx2-bb/container/src/slotmap.rs
iceoryx2-bb/container/src/vec.rs
iceoryx2-bb/container/tests/flatmap_tests.rs
iceoryx2-bb/container/tests/queue_tests.rs
iceoryx2-bb/container/tests/slotmap_tests.rs
iceoryx2-bb/container/tests/vec_tests.rs

This PR implements the runtime fized-size flatmaps (`RelocatableFlatMap` and `FlatMap`). Additionally, the last commit makes the documentation of all runtime fixed-size containers visible by mainly removing the `details` module. Please check the documentation if these changes are suitable; if not, they can be easily reverted.
Closes #808

[#808] runtime fixed-size flatmaps

---

Cargo.Bazel.lock
WORKSPACE.bazel
doc/bazel/README.md
doc/release-notes/iceoryx2-unreleased.md
iceoryx2-ffi/cxx/CMakeLists.txt
iceoryx2-ffi/cxx/README.md
internal/scripts/ci_build_and_install_iceoryx_hoofs.ps1
internal/scripts/ci_build_and_install_iceoryx_hoofs.sh
package.xml

This PR makes iceoryx2 depend only on the iceoryx_hoofs subset which are used by the C++ bindings.
Closes #824

[#824] Use minimal iceoryx_hoofs subset for iceoryx2 C++ bindings 

---

doc/release-notes/iceoryx2-unreleased.md
examples/Cargo.toml
examples/rust/discovery_service/discovery_service_client.rs
iceoryx2-services/discovery/src/service_discovery/service.rs
iceoryx2-services/discovery/src/service_discovery/tracker.rs
iceoryx2-services/discovery/tests/service_discovery_service_tests.rs

- Added a `RequestResponse` server in `discovery_service.rs` that responds with a list of all currently tracked services.
- This allows clients to query the discovery layer for runtime visibility into what services are currently active.
- Added a new example client under `examples/discovery_service/discovery_service_client.rs` that connects to the server,sends a query, and prints the discovered services.
[changelog]: https://github.com/eclipse-iceoryx/iceoryx2/blob/main/doc/release-notes/iceoryx …

[#777] Request current discovery state from discovery service

---

.github/workflows/build-test.yml
iceoryx2-ffi/c/cmake/install.cmake
iceoryx2-ffi/cxx/cmake/install.cmake

This is a follow up PR to #815 to make the C++ example build in-tree with `fetch_content`.
* [~] Tests follow the [best practice for testing][testing]
Closes #814

[#814] Fix building C++ examples in tree

---

doc/release-notes/iceoryx2-unreleased.md
internal/scripts/cargo_tree.sh

This PR adds a script to help list the dependencies of package groups.
Closes #933

[#933] Add script to list dependencies of multiple packages

---

doc/release-notes/iceoryx2-unreleased.md
iceoryx2-ffi/cxx/tests/src/service_event_tests.cpp
iceoryx2-ffi/cxx/tests/src/service_publish_subscribe_tests.cpp
iceoryx2-ffi/cxx/tests/src/service_request_response_tests.cpp
iceoryx2-ffi/ffi/src/api/node_builder.rs
iceoryx2-ffi/ffi/src/api/port_factory_client_builder.rs
iceoryx2-ffi/ffi/src/api/port_factory_listener_builder.rs
iceoryx2-ffi/ffi/src/api/port_factory_notifier_builder.rs
iceoryx2-ffi/ffi/src/api/port_factory_publisher_builder.rs
iceoryx2-ffi/ffi/src/api/port_factory_server_builder.rs
iceoryx2-ffi/ffi/src/api/port_factory_subscriber_builder.rs

Iox2 947 fix memory leak when port creation fails

---

doc/release-notes/iceoryx2-unreleased.md
iceoryx2-bb/posix/src/scheduler.rs

[#977] Set thread priority correctly, not always min value

---

doc/design-documents/template.md

[#4] Add design doc template

---

iceoryx2-bb/posix/src/thread.rs
iceoryx2-bb/posix/tests/thread_tests.rs

[#962] Handle out-of-bounds cpu core id setting in set

---

doc/release-notes/iceoryx2-unreleased.md
iceoryx2-cli/iox2/src/commands.rs

Filters out duplicate entries in the search path for the `iox2` CLI.
This prevents the discovered commands from being listed multiple times. Can be verified with this command:
```console
cargo run --bin iox2 -- --list
```
Closes #1045

[#1045] Filter out duplicate entries in iox2 search path

---

doc/release-notes/iceoryx2-unreleased.md
iceoryx2-ffi/c/src/api/entry_handle_mut.rs
iceoryx2-ffi/c/src/api/reader.rs
iceoryx2-ffi/c/src/api/service.rs
iceoryx2-pal/posix/src/freebsd/constants.rs
iceoryx2-pal/posix/src/libc/constants.rs
iceoryx2-pal/posix/src/linux/constants.rs
iceoryx2-pal/posix/src/macos/constants.rs
iceoryx2-pal/posix/src/qnx/constants.rs
iceoryx2-pal/posix/src/windows/constants.rs

See title.
Closes #1059
Closes #1061

[#1059] use process local config for `LocalService` in C language binding

---

.github/workflows/build-test.yml
.github/workflows/release.yml
doc/release-notes/iceoryx2-unreleased.md
iceoryx2-ffi/c/src/api/service.rs
iceoryx2-pal/posix/src/freebsd/constants.rs
iceoryx2-pal/posix/src/libc/constants.rs
iceoryx2-pal/posix/src/linux/constants.rs
iceoryx2-pal/posix/src/macos/constants.rs
iceoryx2-pal/posix/src/qnx/constants.rs
iceoryx2-pal/posix/src/windows/constants.rs

[#1059] Backport [#1059 use process local config for `LocalService` in C language binding] to release_0.7

---

.github/workflows/build-test.yml
BUILD.bazel
Cargo.Bazel.lock
Cargo.lock
Cargo.toml
MODULE.bazel.lock
WORKSPACE.bazel
iceoryx2-pal/os-api/BUILD.bazel
iceoryx2-pal/os-api/Cargo.toml
iceoryx2-pal/os-api/bazel_bindgen_workaround.rs
iceoryx2-pal/os-api/build.rs
iceoryx2-pal/os-api/src/c/linux.h
iceoryx2-pal/os-api/src/lib.rs
iceoryx2-pal/os-api/src/linux-bindgen/epoll.rs
iceoryx2-pal/os-api/src/linux-bindgen/mod.rs
iceoryx2-pal/os-api/src/linux-libc/epoll.rs
iceoryx2-pal/os-api/src/linux-libc/mod.rs
internal/scripts/crates_io_publish_script.sh

* `libc` is now an optional dependency and activated only when iceoryx2 is build with the `libc_platform` feature
* introduces a new crate in the platform abstraction layer called `os_api` where all os specific API like `epoll` or qnx pulses can be abstracted
Relates to #961

[#961] introduce linux os api

---

ROADMAP.md

If we want to go into space, we need to support RTEMS ... and we also need to support the Rust based Redox OS.
* [~] Tests follow the [best practice for testing][testing]
Relates to #4

[#4] Add RTEMS RTOS to roadmap

---

Cargo.toml
doc/release-notes/iceoryx2-unreleased.md

… for iceoryx2 workspace
We need the libc dependency with Debug Traits enabled. We enable it explicitly: https://github.com/rust-lang/libc/blob/4d939b0d26d97f8794f14bdf2638e39bf19d4af1/README.md?plain=1#L49
Add `extra_traits` feature to libc dependency.
Closes #1087

[#1087] Enable extra_traits feature for libc dependency

---

examples/cross-language-end-to-end-tests/test_e2e_cross_language_complex_types_publisher_cxx_subscriber_rust.exp
examples/cross-language-end-to-end-tests/test_e2e_cross_language_complex_types_publisher_rust_subscriber_cxx.exp
examples/cross-language-end-to-end-tests/test_e2e_cross_language_container_publisher_cxx_subscriber_rust.exp
examples/cross-language-end-to-end-tests/test_e2e_cross_language_container_publisher_rust_subscriber_cxx.exp

Added cross-language end-to-end tests for the new container examples
* [~] Tests follow the [best practice for testing][testing]
Relates to #1080

[#1080] Add container cross language examples end-to-end tests
